mbta/screenplay

assets/css/place-row.scss
assets/js/components/Dashboard/Dashboard.tsx
assets/js/components/Dashboard/PlaceRow.tsx
assets/tests/components/placeRow.test.tsx

I noticed that flipping the sort order causes the map segments to be facing the wrong direction for some stations. Added a CSS class to flip the image if the sort order is flipped.

fix: Map segment orientation when sorting

---

scripts/fetch_places_and_screens.exs

DUPs can be configured to show data for multiple places near where it is located. This PR modifies the script to split out DUP screens into all places the config references.

tweak: show DUPs in all configured places

---

.gitignore
assets/js/components/Dashboard/ScreenDetail.tsx
assets/js/models/screen.ts
config/dev.exs
lib/screenplay/config/local_fetch.ex
lib/screenplay/config/s3_fetch.ex
lib/screenplay_web/controllers/dashboard_api_controller.ex

**Asana task**: [[Screenplay] Indicate location on screen name](https://app.asana.com/0/1185117109217413/1202505849835058/f)
A new file needs to be created for this feature to work as expected. That file (`screen_locations.json`) will live in the same directory as `places_and_screens.json`. The contents are a list of objects with the shape `{ "id": "1", "location": "Test" }`. Each object will map to screens with the same id in `places_and_screens.json`. The frontend will then render the location in the accordion panel. If no location exists for a screen, only the screen type is displayed. 
No locations are needed for the config to work. `screen_locations.json` can be an empty list and each screen will render only the screen type.

feat: Support locations for screens

---

assets/js/components/Dashboard/PaessScreenDetail.tsx

These urls should use https anyway, but Firefox was also not allowing the URLs to be loaded because it doesn't let you load http URLs within an https URL. I tested this in dev by editing the url directly in the html and the signs then loaded properly.
For some reason, this causes a local instance of Screenplay to not be able to load the https signs UI urls even though Firefox apparently allows loading of mixed content when loading localhost but it's more important that dev works correctly and we can work out the local version later. Or one can simply temporarily change the URLs if they wanted to view the renderings locally.

Update Signs UI URLs

---

assets/css/place-row.scss
assets/js/components/Dashboard/Dashboard.tsx
assets/js/constants/constants.ts
assets/js/constants/stationOrder.ts

**Asana task**: [📺▶️ : 🇵🇱 | Add Mattapan Line filter](https://app.asana.com/0/1185117109217413/1202773104374781/f)
This PR adds a filter for Mattapan on the places list. When filtered, the stops are in order and a map segment is displayed.

feat: Mattapan filter

---

assets/js/components/Dashboard/ScreenDetail.tsx

**Asana task**: [Places list: Prevent expanded place row from closing when simulation panels are clicked](https://app.asana.com/0/0/1202839698975983/f)
At the moment, nothing should happen when the ScreenDetail card or simulation is clicked. Adding `stopPropagation` keeps the row from collapsing.

polish: Prevent row collapse when ScreenDetail card is clicked.

---

assets/css/sidebar.scss
assets/js/components/Dashboard/Sidebar.tsx

**Asana task**: [Sidebar: Disable and rename Posted Alerts link](https://app.asana.com/0/0/1202839698975982/f)
Until we start on the Alerts page, the link will not be used. Disabled it until then.

polish: disable Posted Alerts link

---

assets/css/screenplay-container.scss

**Asana task**: [V1 Bus e-ink bug: opening 1624 Blue Hill Ave @ Mattapan Sq makes a horizontal scrollbar](https://app.asana.com/0/0/1202842194729176/f)
Not 100% sure where the extra width was coming from, but hiding the overflow prevents it from appearing. All of our content is contained in the viewport anyway, so no actual content should be cut off.

polish: Horizontal overflow for v1 sims

---

assets/js/components/Dashboard/PlaceRow.tsx

[Notion](https://www.notion.so/mbta-downtown-crossing/Columns-on-places-list-first-one-is-too-short-mode-is-too-long-13867c42f2a2408094d2784abc5e45fa)
Name column was too narrow and route/mode column was too wide. This also fixed an issue with wrapping station names causing `inlineMap` segments to be the wrong size.

polish: Adjust PlaceRow column widths

---

scripts/fetch_places_and_screens.exs

**Asana task**: ad hoc / pre-launch polish
This adds a line to the script that generates places_and_screens.json, making it respect the new `hidden_from_screenplay` config field when fetching screens config.
Plus one small refactor to the script: replaced an `Enum.reduce` with an `Enum.flat_map` that does the same thing.
Tested informally by hiding 2 screens in screens-dev admin and running the script pointed at dev with some debug lines:
```
$ mix run scripts/fetch_places_and_screens.exs --environment dev
BEFORE screen count: 206
AFTER screen count: 204
```

tweak: Omit hidden-from-screenplay screens when generating places_and_screens.json

---

assets/css/place-row.scss
assets/js/components/Dashboard/PlaceRow.tsx
assets/tests/components/placeRow.test.tsx
lib/screenplay_web/templates/unauthorized/index.html.heex

[Polish task](https://www.notion.so/mbta-downtown-crossing/c879496a39fd4e62969fe1d0eecdfa01?v=f7ad0a8b40784aaebb1aaac3d417bb39&p=dff514270aa64b34b98d4e69f4072de8&pm=s). 
Convert screen-types spacer from text to element to add classname + padding. 
Reduced font-weight for screens / status text.
Changed "unauthorized" message to have my email instead of Paul's.

Column text styling

---

assets/css/place-row.scss

[Task in Notion](https://www.notion.so/mbta-downtown-crossing/Missing-subtle-dimension-on-rows-7e189e6ff11447648f1075044e3bacfa)
Evidently `border-radius`, `border-image-source`, and `linear-gradient` don't play too nicely together. The current solution works but is missing the gradient on the sides and only shows it along the top of a row.

[Screenplay Polish] - Missing subtle dimension on rows

---

assets/css/place-row.scss
assets/css/screen-detail.scss
assets/js/components/Dashboard/PlaceRow.tsx
assets/js/components/Dashboard/ScreenDetail.tsx

[Notion](https://www.notion.so/mbta-downtown-crossing/Solari-screens-should-stack-side-by-side-072a894f2d8440a4ae262f6b1fb04e4c)
If the screen type is Solari, we want to wrap all said Solari screens in a different layout component that lets the screen cards flex and fill a row. (Currently, we only ever expect to see <2 Solari screens, and the flex method looks good up to 3 screens.)

Add special layout for Solari for screen cards

---

assets/css/filter-dropdown.scss

**Asana task**: ad hoc
`!important` is necessary to override bootstrap's base styles.
Before
After

fix: Force filter dropdown button to not have left border-radius when a filter is selected

---

assets/css/place-row.scss

**Asana task**: [[Screenplay Bug] Report a Problem button doesn't work when a filter is applied](https://app.asana.com/0/1185117109217413/1203065546384045/f)
Height should be just as big as the border, not the whole panel 🤦 . Border color is still a question, but I want to fix this bug now so dev is in a good state.

polish: Fixed pseudo border height so it doesn't cover up the panel.

---

scripts/fetch_places_and_screens.exs

For Aquarium (and potentially others in the future), we need a way to add Ferry to the list of routes. The most straightforward way to do this is to add these special cases as patterns in a function. The `add_routes_to_stop` function here will be the function we use to do that.

tweak: Add Ferry to stops in script

---

.gitignore
README.md
assets/js/components/Dashboard/PlaceRow.tsx
assets/js/models/place.ts
config/dev.exs
lib/screenplay/config/local_fetch.ex
lib/screenplay/config/s3_fetch.ex
lib/screenplay_web/controllers/dashboard_api_controller.ex

**Asana task**: [[Screenplay] Group screens by stop ID, not stop name](https://app.asana.com/0/1185117109217413/1203093788250254/f)
I missed this part of the `Done When` on the above task. This is done similarly to how screen locations are added. A file called `place_descriptions.json` will be created that, at the very least, needs to have an empty array `[]`. See README for more info. If a description is provided, `PlaceRow` will show `<place_name> <description>`.

feat: Add optional place descriptions

---

.envrc.template
assets/js/components/Dashboard/AlertCard.tsx
assets/js/components/Dashboard/AlertsPage.tsx
assets/js/components/Dashboard/Dashboard.tsx
assets/js/components/Dashboard/PaessScreenDetail.tsx
assets/js/components/Dashboard/ScreenDetail.tsx
assets/tests/components/alertCard.test.tsx
assets/tests/components/alertsPage.test.tsx
assets/tests/components/placeRow.test.tsx
config/runtime.exs
lib/screenplay/alerts/screens_by_alert.ex
lib/screenplay/v3_api.ex
lib/screenplay_web/controllers/alerts_api_controller.ex
lib/screenplay_web/controllers/dashboard_controller.ex
lib/screenplay_web/templates/dashboard/index.html.eex

**Asana task**: [[Screenplay] Include "places" and "screens" counts on alerts](https://app.asana.com/0/1185117109217413/1202932249366380/f)
`AlertCard`s now display the number of screens and places that are affected by the alert. 3 new ENV variables have also been added: `API_V3_URL`, `SCREENS_URL`, and `SIGNS_UI_URL`. These URLs  used to be picked conditional in code based on environment. They now live in terraform so each environment will automatically pick the correct URL. That PR is [here](https://github.com/mbta/devops/pull/675) and will need to be merged and applied before merging this PR.

feat: Add place and screen count to AlertCard

---

assets/js/app.tsx
assets/js/components/Dashboard/AlertsPage.tsx
assets/js/components/Dashboard/PaessScreenDetail.tsx
assets/js/components/Dashboard/ScreenDetail.tsx
assets/js/components/Dashboard/Sidebar.tsx
lib/screenplay_web/plugs/metadata.ex
lib/screenplay_web/router.ex
lib/screenplay_web/templates/dashboard/index.html.eex
lib/screenplay_web/templates/layout/app.html.heex

**Asana task**: [[Screenplay] 🐞 Username not initialized from alerts page](https://app.asana.com/0/1185117109217413/1203236363940422/f)
The solution for communicating ENV variables and similar constants was originally borrowed from the way the screens app. That method is fine for applications that only use a single page with no routing. For Screenplay, when the application loaded from the `/alerts` URL, some things like `username` and `environment_name` were not being picked up because that controller did not add them to `conn.assigns`. A new module plug has been added so we no longer have to remember to add values at the controller level. In this plug, it grabs all necessary values the same way the `DashboardController` was. Instead of adding these as data attributes on the `dashboard` …

tweak: Metadata Module Plug

---

config/prod.exs

**Asana task**: [[Screenplay] Fix http / https routing](https://app.asana.com/0/1185117109217413/1203259339371911)
We have a plug in all CTD apps called `redirect_prod_http`, which checks to see whether there's a `redirect_http` in the app config and then runs a redirect from the nonsecured to the secured url. We had forgotten to set the config variable to true for prod! 💡

bugfix: Needed to set redirect_http for prod!

---

assets/js/components/App.tsx
assets/js/components/Dashboard/AlertsPage.tsx
assets/js/components/Dashboard/Dashboard.tsx
assets/js/components/Dashboard/PlacesPage.tsx
assets/tests/components/alertsPage.test.tsx
assets/tests/components/placesPage.test.tsx
assets/tests/utils/RenderRouteWithOutletContext.tsx

In order to complete [this task](https://app.asana.com/0/1185117109217413/1203236363940419/f), the way we implement navigation needed to be refactored a bit. 
Before this change, we were doing some work manually that `react-router` normally takes care of. To fix this, I removed all custom conditional rendering on the `Dashboard` and instead added some additional routes to `App.tsx`. The top level `*` route renders the `Dashboard`. Under that are two nested routes for `PlacesPage` and `AlertsPage`. When using nested routes, you no longer reference components in the parent route's component. Instead, you just render `<Outlet />`. `<Outlet />` will be replaced by the child route's element when navigating between routes. 
In lieu of passing props to `AlertsPage` and …

tweak: Refactor navigation

---

assets/css/dashboard/alert-details.scss
assets/css/dashboard/alerts-page.scss
assets/css/screenplay.scss
assets/js/components/App.tsx
assets/js/components/Dashboard/AlertDetails.tsx
assets/js/components/Dashboard/AlertsPage.tsx
assets/js/components/Dashboard/Dashboard.tsx
assets/js/components/Dashboard/PlacesPage.tsx
assets/js/util.ts
assets/tests/components/alertsPage.test.tsx
assets/tests/components/placesPage.test.tsx
assets/tests/utils/RenderRouteWithOutletContext.tsx
lib/screenplay_web/router.ex

**Asana task**: [Alert details / alert places list to be at new URL](https://app.asana.com/0/1185117109217413/1203236363940419/f)
Task above lays out the reason for this change very well.
Implementation for it was fairly straightforward after the refactor to navigation. Only thing that may look odd is this new URL is its own `Route` on the same level as `/alerts`. I could not find a good place to render the `<Outlet />` on the `AlertsPage` when I tried to add it as a nested route. It would require more conditional rendering, which we are trying to avoid. `AlertDetails` also needs all of the same context values present in the `Outlet` in `Dashboard`. If you feel strongly above making it a nested route, I can give that a shot and we can decide the best method.
This new URL works if you …

tweak: Alert Detail URL change

---

config/config.exs
config/dev.exs
config/prod.exs
config/test.exs
lib/screenplay_web/controllers/auth_controller.ex
lib/screenplay_web/router.ex

**Asana task**: [[Screenplay] Fix http / https routing](https://app.asana.com/0/1185117109217413/1203259339371911)
Setting the https port and setting force_ssl like so seems to resolve the redirect issue in a production test env. This follows part of the pattern suggested by the Phoenix boilerplate `prod.exs`, but some of the fields (keyfile / certfile) were not needed.

bugfix: http to https redirect

---

config/config.exs
config/dev.exs
config/prod.exs
config/test.exs
lib/screenplay_web/controllers/auth_controller.ex
lib/screenplay_web/router.ex

Reverted piecemeal because I accidentally didn't do a squash merge of the original PR 😵‍💫
Merging the PR caused dev deploy to hang/fail after several hours. Not 100% sure why, but my guess is that the health-check endpoint used to confirm the new task is working was responding with an HTTP -> HTTPS redirect.
[Original PR commits](https://github.com/mbta/screenplay/pull/166/commits)

Revert hp/http-redirect-bug

---

assets/js/components/Dashboard/ReportAProblemButton.tsx
assets/tests/components/reportAProblemButton.test.tsx
lib/screenplay_web/controllers/dashboard_controller.ex
lib/screenplay_web/plugs/metadata.ex
lib/screenplay_web/router.ex
lib/screenplay_web/templates/layout/app.html.heex

**Asana task**: [[Screenplay] For PIOs, "report a problem" button goes to new private slack channel](https://app.asana.com/0/1185117109217413/1203365549546187/f)
PIOs now have a new private Slack channel to use when communicating with our team. This PR changes the Report a Problem button to redirect to it if the logged in user is an admin. The only Screenplay admins are PIOs (and maybe a couple of our team members) so it is safe to assume that an admin has access to the private channel. If you are not an admin, the button continues to redirect you to #screens.

tweak: Report A Problem URL

---

assets/js/components/Dashboard/Dashboard.tsx

Notion [task](https://www.notion.so/mbta-downtown-crossing/The-banner-should-only-persist-40sec-not-2min-616e47fa44334366b728d47f99082c50)
Now that we know that alerts will take no more than 40 seconds to start showing on screens, we no longer need the banner to be visible for 2 minutes.

polish: Alert banner timing

---

assets/js/components/Dashboard/AlertBanner.tsx
assets/js/components/Dashboard/Sidebar.tsx

Notion [task](https://www.notion.so/mbta-downtown-crossing/Trim-backslashes-from-route-conditionals-8f805cbc156e44b8aebe8fdd2ca5153b)
For some conditionals, we are looking for certain routes for special styling or text. This logic is thrown off when there is a trailing `/` on the URL. Because that being present is still a valid URL, I trimmed all backslashes in routes before doing any comparisons.

polish: Trim backslashes in route conditionals

---

assets/css/alert-card.scss

Notion [task](https://www.notion.so/mbta-downtown-crossing/BL-and-Bus-pill-in-alert-list-are-a-different-size-59cdde9033764addaa5445a998ec89a4)
The BL and Bus pills have a shadow that is not on the other pills. Hardcoding pill sizing was making those two pills appear smaller than the others. With these CSS adjustments, we can keep the shadow while allowing the pills to be the same size as the rest.

polish: AlertCard route pill sizing

---

assets/js/components/Dashboard/PlacesActionBar.tsx

[Notion Task](https://www.notion.so/mbta-downtown-crossing/Mismatched-wording-for-Places-8e4f1201930d4632b24463cd2ff578fa)
Use place/places instead of station/stations on the places action bar

polish: Change station/stations to place/places

---

assets/js/components/Dashboard/AlertCard.tsx

Notion [task](https://www.notion.so/mbta-downtown-crossing/Don-t-show-highlight-animation-when-alert-duration-changes-ef478a2f0045443092be5ee8cbb40b47)
When alerts are created with an end date of `Until later today`, the end date is changed by the API once a minute of two. This is causing animations to happen too frequently for those alerts. Because we have no way of determining if an alert was created using `Until later today`, the best thing to do is only consider start date in the animation hook.

polish: AlertCard animation

---

assets/css/alert-banner.scss

Notion [task](https://www.notion.so/mbta-downtown-crossing/Banner-doesn-t-stick-when-page-is-scrolled-f93f13fd55124e9980d263dbd2ea840c)
Made the `AlertBanner` always stick to the top of the screen so it is visible after scrolling.

polish: Sticky AlertBanner

---

assets/js/components/Dashboard/AlertsPage.tsx

Notion [task](https://www.notion.so/mbta-downtown-crossing/Unexpected-end-date-sort-ordering-9ab2e5ec271140a3810e220290b15505)
The `AlertsPage` logic we had before wasn't quite right when comparing a recurring alert. Switching to `moment` makes comparison much easier with the help of the many helper functions.

polish: AlertsPage sorting

---

assets/js/components/Dashboard/AlertBanner.tsx

**Notion [task](https://www.notion.so/mbta-downtown-crossing/Screenplay-Alerts-Polish-d3f44e3eec4346a19f31f24f75fa1ae6?p=09b494315f4143f8b916673ae8eb2a31&pm=s)**
The banner should be visible and counting down until 40seconds after the alert change (closed/updated/posted). (It's likely that the countdown will never start at 40s because it takes several seconds for posts to appear in Screenplay.)
If a new change overrides the banner, the countdown is also updated.

Polish: Banner actively counts down based on latest alert change

---

assets/js/components/Dashboard/AlertBanner.tsx
assets/js/components/Dashboard/Dashboard.tsx
assets/js/util.ts
lib/screenplay/util.ex
lib/screenplay_web/controllers/alerts_api_controller.ex

[Notion](https://www.notion.so/mbta-downtown-crossing/Screenplay-Alerts-Polish-d3f44e3eec4346a19f31f24f75fa1ae6?p=369ad44cc004411b8d9a173ae80b07ff&pm=s)
Both the banner and alert list should be filtered down by alert effect (only the effects that appear as alerts on screens) and whether it is happening now.
Additional changes: banner should not count down. Also, the banner should correctly identify SL alerts.

Polish: the alerts for banner & list are filtered on the backend

---

assets/js/components/Dashboard/AlertsPage.tsx
assets/js/hooks/useScreenplayContext.tsx
assets/tests/components/alertsPage.test.tsx

**Asana task**: [ad-hoc-ish](https://mbta.slack.com/archives/C02SXM166N8/p1674761551378159)
For the `AlertsPage`, we now group alerts in two "sections": one has alerts on screens, the other has alerts not on screens. Within the sections, we are still sorting alerts by end date. With this change, we also are removing custom sorting on this page. For now, alerts will always be sorted in the specific way described above.

polish: group alerts by screen count

---

assets/css/alert-banner.scss

**Asana task**: ad hoc
The alert update banner had the same z-index as the inline track segment graphics. This fixes that by giving it an ***even bigger z-index!!***

fix: Ensure alert update banner draws on top of everything

---

lib/screenplay_web/templates/layout/app.html.heex

Name was using underscores instead of hyphens like we use on the others.

fix: Fullstory meta name

---

assets/js/app.tsx

I initially added this conditional because it _seemed_ like a good thing to do. I think it might be causing Fullstory to never initialize. Unfortunately, this is not possible to test anywhere but prod.

fix?: Fullstory init conditional

---

assets/js/components/Dashboard/ScreenDetail.tsx

**Notion task**: [Screenplay displays v2 DUPs correctly](https://www.notion.so/mbta-downtown-crossing/Screenplay-displays-v2-DUPs-correctly-19abf681ecdd42c6ab1df7b13a2be6f0?pvs=4)
Added ad loop text to `dup_v2`.

polish: DUP v2 ad loop text

---

lib/screenplay_web/templates/unauthorized/index.html.heex

There's been more Screenplay traffic lately, with a lot of folks requesting access to Screenplay. It's not needed, but the unauth page doesn't make that clear. Updated with pointers

[minor fix] Give helpful pointers on the "unauth" page

---

scripts/fetch_places_and_screens.exs

Some config changes happened when the new bus signs were rolled out. The script needed some changes to allow us to get the data we needed to show the bus signs.

Fixed script to account for config changes in new bus signs.

---

assets/css/screen-detail.scss

**Asana task**: [[Pre-Fare Alerts] "New look" in Screenplay](https://app.asana.com/0/1185117109217413/1205259333913109/f)
This change won't be needed until https://github.com/mbta/screens/pull/1837 is merged. With the new designs for PreFare, the simulation source is a little taller. To keep the vertical scrollbar from showing, I increased the height a touch.

tweak: PreFare iframe container height.

---

scripts/fetch_places_and_screens.exs

**Asana task**: [Update Places and Screens JSON script](https://app.asana.com/0/1185117109217413/1205353331802631/f)
Eazy peazy. While this does correctly import triptychs into the data, the screen sims do not look good. Handled in another task.

tweak: add Triptychs to places and screens script

---

lib/screenplay/outfront/sftp.ex

Log if outfront ssh key is NOT a valid string; log connection error

[tweak] Log issues with making SFTP connection

---

assets/js/components/App.tsx
assets/js/components/Dashboard/PendingScreensPage.tsx
assets/js/components/Dashboard/Sidebar.tsx
lib/screenplay_web/controllers/config_controller.ex
lib/screenplay_web/router.ex
lib/screenplay_web/templates/config/index.html.eex
lib/screenplay_web/views/config_view.ex

**Asana task**: [[Perm config] Create new app routing](https://app.asana.com/0/1185117109217413/1205709923095884/f)
Adds new frontend routes and sidebar items for the "Pending" and "Configure" pages. Also adds a minor backend change to support the routing/urls.

New routing for Permanent Config

---

config/dev.exs
lib/screenplay_web/auth_manager/auth_manager.ex
lib/screenplay_web/auth_manager/ensure_screenplay_admin_group.ex
lib/screenplay_web/plugs/metadata.ex
test/support/conn_case.ex

**Asana task**: [Create Cognito group for Permanent Configuration Tool](https://app.asana.com/0/1185117109217413/1205700210661282/f)
Description
This PR adds a new cognito group for users that will be allowed to configure new screens through Screenplay.
Related Terraform changes: https://github.com/mbta/devops/pull/1344

Add new group for permanent config

---

config/runtime.exs
lib/screenplay/config/config.ex
lib/screenplay/config/s3_fetch.ex
lib/screenplay_web/controllers/config_controller.ex
lib/screenplay_web/router.ex

**Asana task**: [S3: Use ETag to verify latest version is being edited ](https://app.asana.com/0/1185117109217413/1205700210661288/f)
Description
This is a basic POC for how we can use the `ETag` field returned from calls to S3 to understand if the config has changed since a user began preparing to add (or remove) a screen's config.
Currently, the logic simply allows or disallows an update based on the given and current value of the ETag but I'm not 100% sure if that's the direction we want to take things. 
The current approach also still allows for a race condition if two clients tried to make updates to the screens config at the same time. Not sure how much we need to worry about that at this point given our limited user pool, but we could ensure requests are handled serially by passing …

[WIP] POC for using ETag to verify screens config version

---

assets/css/place-row.scss
assets/css/screenplay.scss
assets/js/components/Dashboard/PlaceRow.tsx
assets/js/components/Dashboard/PlaceRowAccordion.tsx
assets/js/components/Dashboard/PlacesPage.tsx
assets/js/components/Dashboard/ScreenDetail.tsx
assets/js/util.ts
assets/tests/components/placeRow.test.tsx
assets/tests/components/placeRowAccordion.test.tsx

**Asana task**: [Update place row component](https://app.asana.com/0/1185117109217413/1205552592584843/f)
There are 4 primary goals for these updates
1. Change `disabled` logic so it is read from `props`
2. Add a `select-box` variant
3. Move as much `Accordion` logic out as possible so the component is more reusable
4. Maintain all existing functionality 
The original `PlaceRow` component made the assumption that it would always be used in an `Accordion`. That is no longer the case in Permanent Configuration. We now need the ability to use this component without any accordion logic. This was a lot more work than I anticipated, mostly due to issues with hooks and deciding where accordion logic needed to live.
The solution I went with is moving all accordion logic into the `PlacesList`. …

refactor: PlaceRow component

---

assets/js/components/App.tsx
assets/js/components/Dashboard/PermanentConfiguration/ConfigureScreensPage.tsx
assets/js/components/Dashboard/Sidebar.tsx

**Asana task**: [Fetch stations logic](https://app.asana.com/0/1185117109217413/1205973195471517/f)
Added a function for fetching station list need on future config pages. Subway will be easy because we hold all subway stations in app state. We simply need to get that list and filter it down.

feat: Fetch station list for config pages

---

config/config.exs

I found a missing prod config while trying to deploy the feature branch to dev-green. After adding this, the prod deployment will work as expected.

fix: Added missing prod config.

---

assets/js/components/Dashboard/ScreenDetailActionBar.tsx
assets/js/components/Dashboard/Sidebar.tsx
assets/tests/components/reportAProblemButton.test.tsx
config/dev.exs
lib/screenplay_web/auth_manager/auth_manager.ex
lib/screenplay_web/auth_manager/ensure_screenplay_admin_group.ex
lib/screenplay_web/auth_manager/ensure_screens_admin_group.ex
lib/screenplay_web/plugs/metadata.ex
lib/screenplay_web/router.ex
lib/screenplay_web/templates/layout/app.html.heex
test/screenplay_web/controllers/alerts_controller_test.exs
test/screenplay_web/controllers/dashboard_api_controller_test.exs
test/screenplay_web/controllers/dashboard_controller_test.exs
test/screenplay_web/controllers/outfront_takeover_tool/page_controller_test.exs
test/screenplay_web/ensure_screenplay_admin_group_test.exs
test/screenplay_web/ensure_screens_admin_group_test.exs
test/support/conn_case.ex

In this PR, we ensure users are in the new auth group, `screens-admin`, before accessing either `/pending` or `/configure-screens`. An unauthorized user will not see the buttons in the sidebar and will be redirected to `/dashboard` when trying to access the URLs directly.

feat: Screens Admin auth

---

config/config.exs
config/runtime.exs
lib/screenplay/jobs/takeover_tool_testing_job.ex
lib/screenplay/outfront/sftp.ex

I thought I tested the new automated job in a deployed environment, but I guess not. ~~Now that `sftp_client_module` is needed in module attributes, it can't live in `runtime.exs`. I moved it to `config.exs` instead.~~ Keeping it in the runtime config, but changed from a module attribute back to a helper function.

fix: Missing compile-time env

---

assets/js/components/Dashboard/PermanentConfiguration/Workflows/GlEink/ConfigureScreensPage.tsx

When a location has no more screens after a pending screen was deleted, it was still showing the table headers. Fix conditional so it does not consider deleted pending screens as a row to display.

fix: Table header conditional render

---

assets/js/components/OutfrontTakeoverTool/OutfrontTakeoverTool.tsx

The state was not being set early enough and was causing some child components to error when rendering. Moved the fetch to the constructor so it is ready before child components render.
[Sentry error](https://mbtace.sentry.io/issues/5111135163/?alert_rule_id=9754397&alert_type=issue&environment=prod&notification_uuid=0106feac-205e-4916-ae9a-71b5638ca730&project=6061951&referrer=issue_alert-slack)

fix: state initialization causing mounting issue

---

.github/dependabot.yml

I noticed a package warning while compiling locally and then realized dependabot is not even set up here. Adding it so we can be more aware of big updates. The PR limit I picked was arbitrary so open to changing it. I also chose to ignore minor updates. This should prevent us from getting overwhelmed by these PRs.

feat: Add dependabot

---

.github/workflows/asana-merged.yml
.github/workflows/asana-pr-opened.yml

This turns off the asana integration for dependabot PRs, since they don't run with the necessary permissions.

ignore asana workflows on dependabot branches

---

lib/screenplay_web.ex
lib/screenplay_web/auth_manager/error_handler.ex
lib/screenplay_web/auth_manager/pipeline.ex
lib/screenplay_web/controllers/auth_controller.ex

Was finally able to discover the cause of some [Sentry errors](https://mbtace.sentry.io/issues/5102241771/events/a8c2509681314021885c47f6181fef43/) with terribly unhelpful stack traces. Basically, our session TTL was only 5 minutes. Because we have an auth enforced endpoint that is requested every 4 seconds, this throws a ton of errors if the tab is left open. Users should be able to leave the app open without worrying about this every 5 minutes. Bumped it up to 30 days (same as Glides) to help with this. 
In the future, we will consider storing refresh tokens in the DB and refreshing sessions before they expire.

fix: User Session TTL

---

assets/js/components/Dashboard/ScreenDetailActionBar.tsx
assets/tests/components/reportAProblemButton.test.tsx
config/dev.exs
lib/screenplay_web/auth_manager/auth_manager.ex
lib/screenplay_web/auth_manager/ensure_pa_message_admin.ex
lib/screenplay_web/auth_manager/ensure_screenplay_admin_group.ex
lib/screenplay_web/auth_manager/ensure_screenplay_emergency_admin_group.ex
lib/screenplay_web/plugs/metadata.ex
lib/screenplay_web/router.ex
lib/screenplay_web/templates/layout/app.html.heex
test/screenplay_web/controllers/alerts_controller_test.exs
test/screenplay_web/controllers/dashboard_api_controller_test.exs
test/screenplay_web/controllers/dashboard_controller_test.exs
test/screenplay_web/controllers/outfront_takeover_tool/page_controller_test.exs
test/screenplay_web/ensure_pa_message_admin_test.exs
test/screenplay_web/ensure_screenplay_emergency_admin_group_test.exs
test/support/conn_case.ex

**Asana task**: [Permission needs for Screenplay](https://app.asana.com/0/1185117109217413/1206790423002398/f)
In the new PA Messaging integration, only users with the `pa-message-admin` can access the tool. This PR adds all of the necessary auth needed to check permissions when implementation for the feature starts.

Auth needs for PA Message Creation

---

assets/js/components/Dashboard/PermanentConfiguration/Workflows/GlEink/GlEinkWorkflow.tsx

**Asana task**: Permanent Config GL E-Ink QA (Too-strict screen ID validations)
The validation code enforced a particular format on the GL e-ink screen IDs, but we don't need that.
---
Notes for posterity:
- The other validation issue found during eng QA, where duplicate screen IDs were not always caught, was actually just one more symptom of the auth issue that Christian fixed in #277.
- I originally went down a rabbit hole trying to fix a large number of issues with state value mutation on the client, but ended up dropping that work in favor of a more surgical fix. In case we do end up finding problems caused by the mutations in the future, I've pushed my WIP, semi-broken code to the [jz/fix-pending-screen-validation](https://github.com/mbta/screenplay/compare/permanent-configuration...j …

fix: Allow screen IDs to have any format

---

.github/dependabot.yml

Dependabot isn't successfully retrieving updates because it doesn't know where to look for Phoenix upgrades. These are local dependencies anyway so can just ignore them.

fix: Ignore local dependencies in dependabot.

---

assets/js/components/Dashboard/PermanentConfiguration/PlacesSearchBar.tsx

[Notion](https://www.notion.so/mbta-downtown-crossing/Select-Stations-Search-bar-loses-focus-after-selection-via-search-bar-d9465c320e2d403390a8735f9b7a4b83?pvs=4)
Adds `autofocus` to the search bar.

QA: Autofocus search bar.

---

assets/js/app.tsx
assets/js/components/Dashboard/PlacesPage.tsx
assets/package-lock.json
assets/package.json

This PR adds the FullStory integration to our Sentry initialization. Unfortunately, we do not track FullStory sessions in our dev environments and FullStory is configured to prevent session capturing for localhost so I'm not sure how to verify the integration works unless we deploy to prod. I can confirm that Sentry is still receiving events even if FullStory session URLs don't exist. https://mbtace.sentry.io/issues/5249154602/events/22a637e1840947da88428030d55913ba/.
---
- https://app.asana.com/0/0/1207153943656479

feat: Sentry FullStory integration

---

scripts/pull_configs.sh

This adds a clause to the setup script so that it downloads the files if they don't already exist.

fix pull_configs script

---

lib/screenplay/outfront_takeover_tool/alerts/reminders.ex

This fixes the slack reminder logic to correctly suppress reminders when running locally with no `SLACK_WEBHOOK_URL` environment variable set. Note that the default value in `Application.get_env` was not doing anything, since there's always a value present from `config/runtime.exs`, even if it's `nil`.

fix slack reminder errors when running locally

---

assets/css/screen-detail.scss
assets/css/screen-simulation.scss
assets/js/components/Dashboard/PlaceRow.tsx
assets/js/components/Dashboard/PlaceRowAccordion.tsx
assets/js/components/Dashboard/ScreenDetail.tsx
assets/js/constants/constants.ts
assets/js/util.ts
scripts/build_places.exs

~~There is some existing duplicative logic here around screen types and how certain ones may be displayed differently on the frontend, which I haven't yet attempted to clean up, but I did rename some things to hopefully make the intent clearer.~~
When a config migrated using https://github.com/mbta/screens/pull/2030 is loaded into the updated places-and-screens script, and Screenplay is pointing to an instance of Screens that has the changes in https://github.com/mbta/screens/pull/2039, this branch creates the following result:
Reasons this still looks a bit weird:
* Both the old `solari` and new `busway_v2` screens are displayed at once. In production I don't think this will ever be the case, as one of the two will always be `hidden_from_screenplay`, and there will be a "cutover" at some …

chore: support Busway v2 screens

---

assets/js/components/Dashboard/Sidebar.tsx

Fixes the emergency takeover link on the sidebar, which was relying on the recently-changed root redirect. This points the link directly at the takeover page.

fix emergency takeover link

---

assets/js/components/OutfrontTakeoverTool/OutfrontTakeoverTool.tsx

This deals with a race condition when loading the takeover page. If the alerts data loads before the stations data, the page will crash while rendering. This waits until the stations data is loaded before rendering the page, avoiding the issue.
Note: This looks like a more extensive diff than it is. The only change in the render path is making all the content conditional on the state value.

fix race condition in takeover tool

---

assets/css/app.scss
assets/js/components/OutfrontTakeoverTool/ConfirmationModal.tsx

Fixes the styling of the confirmation modals in the outfront takeover tool. This mostly replicates the original style, but makes a few simplifications.

fix takeover tool modal styles

---

config/config.exs
lib/screenplay_web/auth_manager/auth_manager.ex
lib/screenplay_web/auth_manager/error_handler.ex
lib/screenplay_web/auth_manager/pipeline.ex
lib/screenplay_web/controllers/auth_controller.ex
mix.exs
test/screenplay_web/auth_manager/error_handler_test.exs

Paul S. recently created a [Notion doc](https://www.notion.so/mbta-downtown-crossing/Session-Management-ad53a774fd39462c82146f60700db5fc?pvs=4) that outlines best practices for application session management. In the past, we have seen issues with auth expiring way too early and the band-aid fix was to arbitrarily increase TTL to get around this. This doc gives recommendations to managing TTLs so that use recommended TTL values and lean on `ueberatuh_oidcc` to keep sessions alive for only as long as they should be.

tweak: Auth rework

---

lib/screenplay/ueberauth/strategy/fake.ex

Forgot a small update to the fake strategy in #348. Without this, the auth redirect never completes because the claims doesn't have the require `iat` key.

fix: Fake ueberauth strategy

---

lib/screenplay_web/controllers/auth_controller.ex

**Asana task**: [SCREENPLAY-2N](https://app.asana.com/0/1185117109217413/1207485011307264/f)
Fixes Sentry issue [SCREENPLAY-2N](https://mbtace.sentry.io/issues/5187288913/?environment=prod&project=6061951).
- Adds fallback function definitions for `request/2` and `callback/2`
- These are called if `/auth/:provider` or `/auth/:provider/callback` are visited by a provider that hasn't been configured

fix: send 404 for /auth/* not handled by ueberauth

---

lib/screenplay/alerts/alert.ex
lib/screenplay/route_patterns/route_pattern.ex
lib/screenplay/v3_api.ex
test/screenplay/alerts/cache_test.exs
test/screenplay/pa_messages/pa_message_test.exs
test/screenplay/v3_api_test.exs

**Asana task**: [[bug] Screenplay forms V3 API urls inconsistently](https://app.asana.com/0/1185117109217422/1203906403602585/f)
- Uses `URI` module to build V3 API URLs
- Adds tests for `build_url` function to verify there are no longer any leading `/`s being inserted into the URLs

fix: use URI module to build V3 API URIs

---

.github/workflows/asana-pr-opened.yml

This should hopefully prevent dependabot from trying to run the workflow it doesn't have secrets available for. Note that the previous attempt didn't work because the branch filter is for the target branch, not the source. The `if` clause is used in the official docs, so should work.

actually skip workflow on dependabot PRs

---

assets/js/components/Dashboard/PaessScreenDetail.tsx

Adhoc
The CSS classes that defined the dimensions was refactored a while ago in #261 but the classname for PAESS iframes was never reassigned which is why we've been seeing weird dimensions.

Fix dimensions for paess iframes

---

assets/js/components/Dashboard/PermanentConfiguration/SelectScreenType.tsx
assets/js/components/Dashboard/PlaceRow.tsx
assets/js/constants/constants.ts

Previously we decided the final "user-facing" name for `solari`/`busway_v2` screens would be "Sectional". This updates Screenplay to use the correct name.

chore: update naming for Sectional screens

---

lib/screenplay_web/controllers/dashboard_controller.ex
lib/screenplay_web/controllers/outfront_takeover_tool/page_controller.ex
lib/screenplay_web/router.ex
test/screenplay_web/controllers/dashboard_controller_test.exs
test/screenplay_web/controllers/outfront_takeover_tool/page_controller_test.exs

**Asana task**: [Revise Screenplay entry URL](https://app.asana.com/0/1185117109217413/1206753590642890/f)
This fixes an issue where the root redirect is gated by the emergency takeover permission, so non-admins don't get redirected to the dashboard. This required moving the redirect to another controller to avoid creating a new scope, since all the `OutfrontTakeoverTool` scopes currently enforce this permission.

relax permissions for root redirect

---

.envrc.template
assets/css/dashboard/new-pa-message-page/new-pa-message-page.scss
assets/js/components/Dashboard/PaMessaging/NewPaMessagePage/MessageTextBox.tsx
assets/js/components/Dashboard/PaMessaging/NewPaMessagePage/NewPaMessagePage.tsx
assets/js/utils/api.ts
config/runtime.exs
lib/screenplay/watts.ex
lib/screenplay_web/controllers/pa_messages_api_controller.ex
lib/screenplay_web/router.ex

This PR adds the ability to preview audio for a PA message. Text that is entered is sent to Watts, which returns an audio file that is played in the browser. An error toast is displayed if the Watts call fails. While this sets up the foundation for what is need in form validation, this doesn't tackle the actual validation on form submit. I felt it was appropriate to save that for the Form Submission task. 
---
- https://app.asana.com/0/0/1207371755597657

feat: Preview Audio

---

lib/screenplay/config/fetch.ex
lib/screenplay/config/local_fetch.ex
lib/screenplay/config/permanent_config.ex
lib/screenplay/config/s3_fetch.ex

**Asana task**: [[extra] Screenplay prod crash in PermConfig when trying to publish changes](https://app.asana.com/0/1185117109217413/1207697513391315/f)
Some context from Slack: https://mbta.slack.com/archives/G012H4G4U06/p1719868261122079?thread_ts=1719859672.363579&cid=G012H4G4U06.
Tl;dr, Ana had trouble publishing screens due to an error when trying to upload a new `places_and_screens` file to S3. Two big problems here:
1. The data we send to S3 wasn't being encoded. That's the reason for the Sentry error.
2. We shouldn't bother with talking to S3 if we know the config isn't changing.
We know the config isn't changing here because Ana checked `Hide on Places page` for each of the pending screens. This results in no changes to `places_and_screens`.

fix: Publish error fixes

---

lib/screenplay/alerts/parser.ex
test/screenplay/alerts/alert_test.exs

[Sentry link](https://mbtace.sentry.io/issues/5578657101/events/19a162f2a5394441834f3caa08dade88/)
The Parser logic assumed we would always receive alerts from the API. Over the weekend, there seems to have been a blip and no alerts were returned. This small tweak should allow the server to respond appropriately in that case.

fix: Handle empty alerts response

---

scripts/build_places.exs
scripts/paess_labels.json

Similar to how other screens can be marked `hidden_from_screenplay`, this enables flagging specific PA/ESS signs that we don't want shown in Screenplay. This fixes the issue that the output of `build_places.exs` was no longer directly uploadable since the addition of the lab sign, and had to be manually tweaked to remove it.
---
- https://app.asana.com/0/0/1207943699921831

fix: ignore lab sign in places script

---

scripts/build_places.exs

I noticed a new row in screenplay-dev-green for Haverhill:
My investigation into this lead to me finding that Haverhill CR is being replaced by a shuttle next rating: https://api-dev-green.mbtace.com/routes?filter[stop]=place-WR-0329. This pushed me to track down how we filter out places in the script and I realized how I did it originally was... unstable. Instead of relying on whether the route ID is a number (why would I do that?), we now look at either route type or route ID. 
I also found that we were removing CR/SL/Bus only places way too early. Because they were removed after only Showtime screens were added to them, we were actually neglected to show a lot of places that have countdown clocks.

fix: Script updates for route filtering and formatting

---

assets/js/components/Dashboard/PaMessagesPage.tsx

Comments out these buttons because they don't do anything yet. They can be shown again when the features they are intended link to are built.

chore: remove "Search" and "Advanced Search" buttons

---

test/screenplay_web/controllers/pa_messages_api_controller_test.exs

Adds test for existing `GET /api/pa-messages` behavior.
Also moves route in router into the scope allowing access with an API key
---
Just some housekeeping leading up to message filtering

feat: test `GET /api/pa-messages`

---

assets/css/dashboard/new-pa-message/new-pa-message-page.scss

Forgot to unhide the calendar icon in webkit browsers. Once I fixed that, I noticed they were black making them hard to see. Once I fixed that, I noticed the positioning was also not right. Position and color should now be consistent across browsers.

fix: positioning and color of webkit calendar icon.

---

lib/screenplay_web/auth_manager/pipeline.ex

When we call `get_session` to grab the `previous_path`, the session is not always ready to be read. This was causing some API calls to fail and get a 302. Adding `fetch_session` to the pipeline will ensure the session is always ready.

fix: Session fetching

---

lib/screenplay/pa_messages.ex
lib/screenplay/pa_messages/pa_message.ex
lib/screenplay/util.ex
lib/screenplay_web/controllers/changeset_json.ex
lib/screenplay_web/controllers/fallback_controller.ex
lib/screenplay_web/controllers/pa_messages_api_controller.ex
lib/screenplay_web/router.ex
test/screenplay/pa_messages_test.exs
test/screenplay_web/controllers/pa_messages_api_controller_test.exs

This PR adds an endpoint that can be used to create new PA messages. Although the client should catch any validation errors before the DB insert, I thought it was appropriate to add some changeset validation.

feat: New Messages backend

---

lib/screenplay/pa_messages.ex
lib/screenplay/pa_messages/pa_message/queries.ex
lib/screenplay_web/controllers/pa_messages_api_controller.ex
test/screenplay_web/controllers/pa_messages_api_controller_test.exs

Updates the `GET /api/pa-messages` endpoint to filter the returned PA Messages based on provided query parameters.
So far the only supported parameters are `state` and `now`. `state` can be used to limit the returned PA Messages to only those which are "past", "active", or "future". `now` is mostly a testing convience but allows passing in a timestamp to be treated as the current time when determining which state a PA Message is currently in.

feat: support filtering by message state (past, active, future)

---

lib/screenplay/pa_messages.ex
lib/screenplay/pa_messages/pa_message/queries.ex
priv/repo/migrations/20240808191935_add_gin_index_to_pa_message_sign_ids.exs
test/fixtures/places_and_screens.json
test/screenplay_web/controllers/pa_messages_api_controller_test.exs

- Adds `sign_ids/2` query which uses the `&&` operator to look for array overlap between a PaMessage's sign_ids field and a list of sign ids passed as an argument into the query function
- Adds parameter parser for `sign_ids` array param
- Adds GIN index on `pa_message.sign_ids` so filters on `sign_ids` do not require a sequential scan of the entire table an index 
https://postgresql.org/docs/16/interactive/functions-array.html
https://postgresql.org/docs/16/interactive/gin-intro.html

feat: support filtering PaMessages by sign ids

---

lib/screenplay/config/places_and_screens.ex
lib/screenplay/config/routes_to_signs.ex
lib/screenplay/pa_messages.ex
test/fixtures/places_and_screens_for_routes_to_signs.json
test/screenplay_web/controllers/pa_messages_api_controller_test.exs

Derives a mapping of route id to pa/ess sign ids from the "places and screens" data.
Uses the mapping of routes to PA/ESS sign ids to expand the the sign filtering to include all signs for all of the routes included in the options passed.
Required adding a `route_ids` field to the `PaEssScreen` struct.

feat: support filtering PaMessages by route

---

assets/js/components/Dashboard/NewPaMessage/NewPaMessage.tsx
assets/js/components/Dashboard/NewPaMessage/StationsAndZones/SelectStationsPage.tsx
assets/js/components/Dashboard/NewPaMessage/StationsAndZones/SelectZonesPage.tsx
assets/js/components/Dashboard/NewPaMessage/hooks.tsx
assets/js/hooks/usePlacesWithPaEss.ts
assets/js/hooks/useRouteToRouteIDsMap.ts

Moves `usePlacesWithPaEss` and `useRouteToRouteIDsMap` to the top-level hooks directory because these are useful beyond just the New PA Message page.
---
I'm using these in #431 and felt like I should move them out of the `NewMessagePage` directory

chore: move NewMessagePage hooks to top level

---

assets/css/app.scss
assets/css/components.scss
assets/css/components/button-group.scss
assets/css/components/button.scss
assets/css/dashboard/pa-messages-page.scss
assets/js/components/Dashboard/PaMessagesPage.tsx
assets/js/utils/api.ts
assets/package-lock.json
assets/package.json
lib/screenplay/pa_messages.ex

- Installs `swr` for data fetching
- Wires up page query param to local state for persisted filters
- Moves some button and button group styles into own stylesheets
- Adds filters to PA Messages page to select which state to limit the displayed PA messages to. Clicking a filter that is already applied clears the filter.
https://github.com/user-attachments/assets/3d3c7a59-2527-4e1a-8db6-ee8808f3a689
<details>
<summary>Loading state 📹 </summary>
https://github.com/user-attachments/assets/fb93e139-8802-4f9c-a57d-31203367ac14
</details>
---
https://swr.vercel.app/

feat: adds UI to filter PA messages on their current state

---

lib/screenplay/pa_messages/pa_message.ex
test/screenplay/pa_messages_test.exs

Added a changeset validator for `start_time`. The client should catch this, but in case it doesn't we will prevent it from being inserted.

feat: start_time changeset validator

---

assets/js/components/Dashboard/NewPaMessage/StationsAndZones/RouteColumn.tsx
assets/js/components/Dashboard/NewPaMessage/StationsAndZones/SelectStationsPage.tsx
assets/js/components/Dashboard/NewPaMessage/StationsAndZones/SelectZonesPage.tsx
assets/js/components/Dashboard/NewPaMessage/StationsAndZones/StationGroupCheckbox.tsx
assets/js/models/screen.ts
assets/js/util.ts
lib/screenplay/config/places_and_screens.ex
lib/screenplay/config/routes_to_signs.ex
lib/screenplay/pa_messages.ex
scripts/build_places.exs
test/fixtures/places_and_screens_for_routes_to_signs.json

When importing locations from alerts, I need to know what direction a sign is configured to show for the route. This change should add this info without breaking any existing code that looked at `route_ids`. This info will also be useful when we fix column organization on the Select Zones page.

chore: Add direction_id to PA/ESS sign configs

---

assets/js/components/Dashboard/ErrorToast.tsx
assets/js/components/Dashboard/NewPaMessage/NewPaMessage.tsx
assets/js/components/Dashboard/NewPaMessage/NewPaMessagePage.tsx
assets/js/components/Dashboard/PaMessagesPage.tsx
assets/js/models/pa_message.ts
assets/js/utils/api.ts
lib/screenplay/pa_messages/pa_message.ex
lib/screenplay/pa_messages/pa_message/queries.ex
priv/repo/migrations/20240812182216_change_datetime_column_names.exs
priv/repo/seeds.exs
test/screenplay/pa_messages_test.exs
test/screenplay_web/controllers/pa_messages_api_controller_test.exs
test/support/factory.ex

This PR changes the columns `start_time` and `end_time` to `x_datetime`. There was a lot of mix and matching between `date`, `time`, and `datetime` so this will align our names for better clarity.

chore: Change column name to match its type.

---

assets/js/components/Dashboard/NewPaMessage/StationsAndZones/SelectZonesPage.tsx

This PR addresses a big ole 🤦 . Accidentally changed a variable [here](https://github.com/mbta/screenplay/blob/a15c3ff18fc48fd705b07b53e02c74a727b36d63/assets/js/components/Dashboard/NewPaMessage/StationsAndZones/SelectZonesPage.tsx#L225) that I shouldn't have. Was causing an error when a GL station was not selected.

fix: Zone filter sorting

---

assets/js/components/Dashboard/NewPaMessage/AssociateAlertPage.tsx
assets/js/components/Dashboard/NewPaMessage/NewPaMessage.tsx
assets/js/utils/api.ts

This PR adds the logic needed to select signs informed by an alert. It filters down by stop > route > direction (if provided in `informed_entities`).
---
- https://app.asana.com/0/0/1208009646310782

feat: Import signs from alert informed_entities

---

assets/js/components/Dashboard/NewPaMessage/NewPaMessagePage.tsx

The priority should only change the interval when it is changed. That change happening in the hook was causing it to change unexpectedly. Moving the `setInterval` to the `PriorityPicker` callback will keep it from changing when it shouldn't.
---
- https://app.asana.com/0/0/1208049255038250

bug: Interval changes unexpectedely

---

.github/dependabot.yml

I want to try out Dependabot's `groups` option so we can reduce the number of PRs it opens. Feel free to call out groups that should be added or groups I added that don't look right.

chore: Add dependabot groups

---

lib/screenplay/pa_messages.ex
lib/screenplay_web/controllers/pa_messages_api_controller.ex
lib/screenplay_web/router.ex
test/fixtures/places_and_screens.json
test/screenplay/pa_messages_test.exs
test/screenplay_web/controllers/pa_messages_api_controller_test.exs

Adds a new API endpoint that allows updating existing PA Messages.
Uses `resources/4` macro to define the index, create, and update methods for the PA Messages API in a standardized way.

feat: api endpoint to update an existing pa message

---

assets/js/components/Dashboard/NewPaMessage/StationsAndZones/SelectZonesPage.tsx
assets/js/constants/constants.ts
assets/js/util.ts

In the original implementation, I designed the page to organize the signs by zone in the same way SignsUI does. This was a misunderstanding and the signs should actually be organized by direction ID. I changed up the logic so the left column is direction 0, middle is 0 and 1, right is 1. 
---
- https://app.asana.com/0/0/1208030889228580

chore: Fix sign columns

---

assets/.eslintrc.js
assets/js/components/Dashboard/AlertDetails.tsx
assets/js/components/Dashboard/AlertNotFoundPage.tsx
assets/js/components/Dashboard/Dashboard.tsx
assets/js/components/Dashboard/NewPaMessage/StationsAndZones/SelectStationsAndZones.tsx
assets/js/components/Dashboard/NewPaMessage/StationsAndZones/SelectStationsPage.tsx
assets/js/components/Dashboard/NewPaMessage/StationsAndZones/SelectZonesPage.tsx
assets/js/components/Dashboard/PaMessagesPage.tsx
assets/js/components/Dashboard/PendingScreensPage.tsx
assets/js/components/Dashboard/PermanentConfiguration/Workflows/GlEink/ConfigureScreensPage.tsx
assets/js/components/Dashboard/PermanentConfiguration/Workflows/GlEink/GlEinkWorkflow.tsx
assets/js/components/OutfrontTakeoverTool/AlertDashboard/AlertDetails.tsx
assets/js/components/OutfrontTakeoverTool/AlertWizard/PickStations.tsx
assets/js/hooks/useUpdateAnimation.tsx
assets/package-lock.json
assets/package.json

I noticed a few "rules of hooks" violations and realized we weren't using the very helpful `eslint-plugin-react-hooks` module to catch these for us.
This installs that package and corrects any outstanding violations of the rules of hooks
https://react.dev/reference/rules/rules-of-hooks
https://github.com/facebook/react/tree/main/packages/eslint-plugin-react-hooks

chore: install eslint-plugin-react-hooks, fix issues

---

lib/screenplay_web/controllers/pa_messages_api_controller.ex
lib/screenplay_web/router.ex
test/screenplay_web/controllers/pa_messages_api_controller_test.exs

Adds a "show" endpoint for PA messages at /api/pa-messages/:id

feat(api): get single pa message by id

---

Dockerfile

The cert bundle has been updated and has a new checksum.
This is currently preventing deploys because we cannot build the Docker image: https://github.com/mbta/screenplay/actions/runs/10530484045/job/29180514837

fix: update amazon cert bundle checksum

---

assets/css/dashboard/new-pa-message/new-pa-message-page.scss
assets/css/dashboard/pa-messages-page.scss
assets/js/components/App.tsx
assets/js/components/Dashboard/EditPaMessage/EditPaMessage.tsx
assets/js/components/Dashboard/EditPaMessage/index.ts
assets/js/components/Dashboard/PaMessageForm/AssociateAlert.tsx
assets/js/components/Dashboard/PaMessageForm/MainForm.tsx
assets/js/components/Dashboard/PaMessageForm/PaMessageForm.tsx
assets/js/components/Dashboard/PaMessageForm/types.ts
assets/js/components/Dashboard/PaMessagesPage.tsx
assets/js/models/pa_message.ts
assets/js/utils/api.ts
lib/screenplay_web/router.ex

- Adds a new EditPaMessage page at `/pa-messages/:id/edit`.
- Fetches the current PA message and pre-populates the PaMessageForm
- Attempts to fetch an associated alert
- Handles the case when a PA message's associated alert has ended and is no longer in the feed.
**Asana task**: [Existing Message Edit Page](https://app.asana.com/0/1185117109217413/1207154234320382/f)

feat: support editing pa messages

---

assets/js/components/Dashboard/PaMessageForm/MainForm.tsx
assets/js/components/Dashboard/PaMessageForm/PaMessageForm.tsx

The `useEffect` based updating of `audioState` was resetting the `audioState` to "outdated" if the message text or phonetic audio were different from their starting values.
This manually sets `audioState` in each place that should cause `audioState` to become "outdated" instead. This is how this state was updated prior to the `useEffect` based refactor.

fix: re-enable review audio

---

assets/.eslintrc.js
assets/js/components/Dashboard/PaMessageForm/SelectStationsAndZones/SelectZonesPage.tsx

Hoping to squash this bug once and for all. Tl;dr, unselecting all signs for a place would cause the place to disappear when changing the route filter. I think the problem was some of the logic in the original `useMemo` needs to change much less frequently than what is returned. I split out that piece into its own and places are no longer disappearing.

fix: disappearing places on SelectZonesPage

---

Dockerfile

The cert bundle has been updated and has a new checksum. This is causing a deploy error in dev.

chore: Update checksum of aws-cert

---

assets/js/components/Dashboard/PaMessageForm/SelectStationsAndZones/SelectZonesPage.tsx

When rendering the `SelectZonesPage`, `selectedRouteFilter` was being assigned to the first route ID in `initialRoutes` before it was sorted. Initializing the labels earlier and using the same variable to initialize and render helps solve this.
I also fixed an issue with all routes showing in the filter list instead of just the routes for the selected screens.
---
- https://app.asana.com/0/0/1208169473836920

fix: SelectZonesPage initial filter value

---

assets/css/dashboard/configure-screens-workflow-page.scss
assets/js/components/Dashboard/PermanentConfiguration/Workflows/GlEink/GlEinkWorkflow.tsx
lib/screenplay_web/controllers/config_html.ex
lib/screenplay_web/controllers/config_html/index.html.eex

While checking out #487, I found some issues in Permanent Config that needed to be fixed.
1. There was an infinite rendering loop when fetching existing screens [here](https://github.com/mbta/screenplay/blob/b4268a540f151649031171da3c1189d955137a8c/assets/js/components/Dashboard/PermanentConfiguration/Workflows/GlEink/ConfigureScreensPage.tsx#L107). A prop in the parent component was constantly having it's reference changed after each fetch. Wrapping in `useMemo` stops it from updating unless it needs to.
2. Styling of the `direction` column was off and the button text was wrapping.
3. Back in #423, we updated the Phoenix view/template structure a bit. This means that any route you visit directly goes through the new `*_html` controller. This was being absent was likely just an oversight.

fix: Permanent Config bugs

---

assets/js/constants/stationOrder.ts

Added a station order for SL. This will only affect the select stations page for PA Messages. I thought about making it work on the Places tab as well but the sort order is alphabetical by default. This feels appropriate given that the filter includes multiple routes.
---
- https://app.asana.com/0/0/1208030889228596

chore: SL Order for PA Messages

---

assets/css/dashboard/new-pa-message/selected-stations-summary.scss
assets/js/components/Dashboard/PaMessageForm/SelectStationsAndZones/SelectedStationsSummary.tsx

Within the "select stations" dialog, the station summary tags now wrap onto a new line instead of the text within them wrapping (and spilling out of their borders).
---
- https://app.asana.com/0/0/1208142586199816

fix: text wrapping inside selected station tags

---

assets/js/components/Dashboard/PaMessageForm/AssociateAlert.tsx
assets/js/components/Dashboard/PaMessageForm/PaMessageForm.tsx

**Asana task**: [bug: UI crash when canceling out of alert linking on PA message form](https://app.asana.com/0/1185117109217422/1208634633982713/f)
This fixes an issue where starting an alert linkage and then canceling would crash the UI. The underlying issue was that the sub-form was directly updating some state on the main form, and so canceling would leave things in an inconsistent state. The fix isolates the sub-form with its own state, which is only applied to the main form when the "Apply" button is pressed.
This also demonstrates an approach to prop handling that I think is generally useful: Rather than passing setters down to sub-components and requiring them to update things directly, it's sometimes nicer to think about passing contextual callbacks (e.g. `onApply`, …

fix crash when canceling alert association

---

assets/js/components/Dashboard/DaysPicker.tsx

**Asana task**: [bug: PA message days picker doesn't reflect saved value on edit](https://app.asana.com/0/1185117109217413/1208634633982718/f)
This fixes a bug where the days picker wouldn't respect the saved value when editing a PA message. Initializes the state based on the incoming prop.

initialize days picker based on current value

---

assets/js/components/Dashboard/IntervalPicker.tsx
lib/screenplay/pa_messages/pa_message.ex

**Asana task**: [bug: PA messages accept negative interval](https://app.asana.com/0/1185117109217413/1208634633982716/f)
This fixes an issue where PA messages would allow setting a negative interval. Enforces validation on the front and back end. Also validates the `priority` field for completeness.

validate PA message interval field

---

lib/screenplay/pa_messages/pa_message/queries.ex
test/screenplay_web/controllers/pa_messages_api_controller_test.exs

**Asana task**: [bug: Can't see PA messages that don't play on the current day](https://app.asana.com/0/1185117109217422/1208664128012797/f)
This fixes an issue where the `current` filter wouldn't show messages that don't play on the current day. Moves the day condition to the `active` filter so it continues to apply there.

fix current PA message filter

---

assets/js/components/Dashboard/PaMessagesPage.tsx

**Asana task**: [Add end information for Alert-associated messages to PA/ESS message page](https://app.asana.com/0/1185117109217422/1208586206997517/f)
When a PA message's end date is linked to an alert, show the alert ID in the listing table.

show alert id in place of PA message end date

---

assets/css/dashboard/filter-group.scss
assets/css/dashboard/new-pa-message/associate-alert-page.scss
assets/css/dashboard/pa-messages-page.scss
assets/css/screenplay.scss
assets/js/components/Dashboard/FilterGroup.tsx
assets/js/components/Dashboard/PaMessageForm/AssociateAlert.tsx
assets/js/components/Dashboard/PaMessagesPage.tsx

Created a new reusable component for filter groups. We use them on 2 (soon to be 3) different pages and they are all implemented separately. This new component will help us maintain the styles. The UX of the filters is unchanged. The UI is also unchanged for the most part outside of some small tweak to bring certain elements in line with the designs.

refactor: Create common FilterGroup component

---

Dockerfile

Hash is outdated. Got the new one using `curl https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem | shasum -a 256`.
Is this check useful? It being outdated results in deployment errors and we end up needing to blindly follow whatever the `curl` command returns anyway.

chore: Remove AWS Cert hash check

---

assets/css/dashboard/pa-messages-page.scss
assets/js/components/Dashboard/KebabMenu.tsx
assets/js/components/Dashboard/PaMessagesPage.tsx

Looks like the recent ESLint update introduced a new rule that we were breaking. Fixed that by moving the `onClick` from a `td` to the kebab menu itself.
I also noticed that the rows are not part of tab navigation. This causes a mouse click to be the only way to navigate to the edit page. Resolved that by making the `Message` column a link.

fix: PaMessagesPage accessibility bug

---

config/runtime.exs
lib/screenplay/application.ex
lib/screenplay/jobs/reminders.ex

While fixing the webhook URL for the Slack app, I remembered this being another good candidate for Oban processing. It still runs once a minute but should only run a single time each minute now. Should prevent the reminder from going off twice when it needs to.

chore: OFM Reminders Job Processing Change

---

assets/js/components/Dashboard/DaysPicker.tsx
assets/js/components/Dashboard/PaMessageForm/MainForm.tsx
lib/screenplay/pa_messages/pa_message.ex

**Asana task**: [bug: Can create a PA message with no days selected](https://app.asana.com/0/1185117109217413/1208664128012801/f)
This adds client-side validation for the day-of-week picker, and also server-side for completeness.

validate that PA messages specify at least one day

---

lib/screenplay/util.ex
lib/screenplay_web/controllers/pa_messages_api_controller.ex

**Asana task**: [Add log entry to capture PA message create/update](https://app.asana.com/0/1185117109217413/1208670991547802/f)
This adds log entries for PA message create/update actions, as specified

log PA message create and update

---

assets/css/pa-messages.module.scss
assets/js/components/Dashboard/MessageTextBox.tsx

Looks like in the switch to CSS modules, the app no longer used the correct BG color for disabled text boxes. Fixed the bg and border colors to match the designs.

fix: Disabled text box styles

---

assets/css/info-popover.module.scss
assets/css/pa-messages.module.scss
assets/js/components/Dashboard/InfoPopover.tsx
assets/js/components/Dashboard/PaMessageForm/MainForm.tsx

Changed the End of service day link to increment day if current time is after 3am. Also added a new popover component so users have a description of what a service day means to us.
---
- https://app.asana.com/0/0/1208759137791893

tweak: End of Service link functionality

---

assets/js/components/Dashboard/PaMessagesPage.tsx

**Asana task**: [Station PA/ESS Status Dashboard Extensions](https://app.asana.com/0/1185117109217413/1207154235176794/f)
Description
Updates the link text for the announcement log and adds a link to the updated device dashboard which includes a new column indicating whether a station's SCU is legacy or new.

Update dashboard links

---

docs/outfront_takeover_tool.md

Includes instructions on accessing the SFTP server interactively. As part of this, I changed how we store the SSH key in 1Password to be a real "SSH key" item, so it works with the 1P SSH agent and doesn't have to be stored unencrypted in a key file somewhere to connect to the server.

doc: add info about the Outfront Takeover Tool

---

config/outfront_takeover_tool_screens.exs

**Asana task**: https://app.asana.com/0/1185117109217413/1208981776139997
Adds South Station as a landscape target for the emergency takeover tool. DUPs were recently installed here and there is a folder set up for them on the SFTP server.

feat: add South Station DUPs to takeover tool

---

assets/css/pa-messages.module.scss

**Asana task**: [Use d﻿ark text for selected items in drop-down list so that the selected item is visible](https://app.asana.com/0/1185117109217413/1208918273737816)
Description
- Allows the selected item text to be more visible since the background color is light

Changed the selected dropdown text to be button-secondary

---

assets/js/components/Dashboard/PaMessageForm/AssociateAlert.tsx
assets/js/components/Dashboard/PaMessageForm/StaticTemplatePage.tsx
assets/js/components/Dashboard/PaMessagesPage.tsx
assets/js/components/Dashboard/PriorityPicker.tsx

**Asana task**: [Language changes to filter PA/ESS and Alerts by time, and describe PA/ESS message type](https://app.asana.com/0/1185117109217413/1208918421836698)
Description
- "Now" switched to "Live"
- "Done" switched to "Past"
- "Current Service Disruption" to "Ongoing service disruption"
- "Planned Service Disruption" to "Upcoming service disruption"

Language changes to filter PA/ESS and alerts by time

---

assets/js/components/Dashboard/PaMessageForm/SelectStationsAndZones/SelectStationsPage.tsx

**Asana task**: [Correct labels used to describe service](https://app.asana.com/0/1209229552734401/1209026414454977)
Description
- Title case for services (e.g. Blue/Red/Green Line)
- Title case for branches (e.g. B Branch, C Branch)
- Changed "Mattapan Line" to "Mattapan Trolley"

Correct labels used to describe service

---

.github/workflows/ci.yml

Copying from https://github.com/mbta/screens-config-lib/pull/52 (insert Write That Down GIF here)
but more or less updating action versions from failing CI runs

ci: Updated action versions

---

assets/js/components/Dashboard/AlertsPage.tsx
assets/js/components/Dashboard/PermanentConfiguration/SelectScreenType.tsx
assets/js/constants/constants.ts
assets/tests/components/alertsPage.test.tsx

**Asana task**: [Fix announcement priority for migrated SCUs](https://app.asana.com/0/1185117109217413/1209272297071108)
Description
- Allow non-PA messages to take priority of 2
- Keep display numbers the same

Renamed Pre-Fare Duo to just be Pre-Fare

---

assets/js/components/Dashboard/PaMessageForm/PaMessageForm.tsx
assets/js/components/Dashboard/PriorityPicker.tsx
lib/screenplay/pa_messages/pa_message.ex
priv/repo/seeds.exs
test/screenplay/pa_messages_test.exs

**Asana task**: [Fix announcement priority for migrated SCUs](https://app.asana.com/0/1185117109217413/1209272297071108)
- Allow non-PA messages to take priority of 2, seems like we already do that in [realtime signs](https://github.com/mbta/realtime_signs/blob/5a5cbb9fea548cd5ab3cd69777ac74fc35432b60/lib/signs/utilities/audio.ex#L187)
- Keep display numbers the same, effectively everything will remain the same but if you look at the API calls underneath to `pa-messages`, priority will now be adjusted when you pick 2, 3, or 4.

Change PA announcement priority from 1, 2, 3, 4 to 1, 3, 4, 5

---

lib/screenplay/places/builder.ex
lib/screenplay/screens_config.ex
test/fixtures/builder/screens_config.json

On-Bus screens do not have a fixed location, so currently there is no sensible way of exposing them in Screenplay.

fix: always hide on-bus screens from place builder

---

.credo.exs
assets/js/components/Dashboard/Dashboard.tsx
assets/js/hooks/useScreenplayContext.tsx
assets/js/models/line_stop.ts
assets/js/models/service_record.ts
assets/js/utils/api.ts
assets/tests/setup.ts
lib/screenplay/application.ex
lib/screenplay/prediction_suppression.ex
lib/screenplay_web/controllers/dashboard_api_controller.ex
lib/screenplay_web/router.ex

**Asana task**: [Prediction suppression: Stops data structure to drive UI](https://app.asana.com/0/1185117109217413/1209637020443919/f)
Description
This adds a new "service record" data structure, which is computed from the API and provides a basis for looking up a particular station/route/direction to determine whether it's the start, end, or middle of its trip. This info will be used to drive the UI for the prediction suppression page.

add data structure for prediction suppression page

---

lib/screenplay/suppressed_predictions.ex
lib/screenplay/suppressed_predictions/suppressed_prediction.ex
lib/screenplay_web/auth_manager.ex
lib/screenplay_web/controllers/fallback_controller.ex
lib/screenplay_web/controllers/suppressed_predictions_api_controller.ex
lib/screenplay_web/router.ex
lib/screenplay_web/templates/layout/app.html.heex
priv/repo/migrations/20250317165509_create_suppressed_predictions_table.exs
test/fixtures/places_and_screens_for_routes_to_signs.json
test/screenplay/suppressed_predictions_test.exs
test/screenplay_web/controllers/pa_messages_api_controller_test.exs
test/screenplay_web/controllers/suppressed_predictions_api_controller_test.exs
test/support/conn_case.ex
test/support/factory.ex
test/support/place_cache_helpers.ex

**Asana task**: [Prediction suppression: Backend data model and API](https://app.asana.com/0/1185117109217413/1209637020443922/f)
- Added suppressed predictions migration for creating table
- Added `suppressed_prediction.ex` DataModel containing `location_id`, `direction_id` and `clear_at_end_of_day` boolean
- Added `suppressed_predictions.ex` Ecto.Repo bridge, with create, update, delete and get/get all functions
- Added `suppressed_predictions_api_controller` handling the calls from `router.ex`
- ~Tests coming soon~

Added data model and API for Prediction Suppression

---

config/runtime.exs
lib/screenplay/jobs/clear_suppressed_predictions.ex
lib/screenplay/suppressed_predictions.ex
test/screenplay/suppressed_predictions_test.exs

**Asana task**: [Prediction suppression: Expire at end of service day](https://app.asana.com/0/1185117109217413/1209637020443934/f)
- Oban Cron Job running at 3am everyday to clear suppressed predictions that have the "clear_at_end_of_day" flag
- Added test to handle new clearing functionality

Added Oban Cron for clearing suppressed predictions

---

.github/workflows/ci.yml

Our CI was failing on `setup-node` due to failed cache, seems like we needed to update the version in order to fix it

Update actions/setup-node from v2 to v4

---

docs/tech_specs/suppressed_predictions_api.md
lib/screenplay/prediction_suppression.ex
lib/screenplay/suppressed_predictions.ex
lib/screenplay/suppressed_predictions/prediction_suppression_utils.ex
lib/screenplay/suppressed_predictions/suppressed_prediction.ex
lib/screenplay_web/controllers/suppressed_predictions_api_controller.ex
lib/screenplay_web/router.ex
test/fixtures/places_and_screens_for_prediction_tests.json
test/screenplay/suppressed_predictions_test.exs
test/screenplay_web/controllers/suppressed_predictions_api_controller_test.exs
test/support/place_cache_helpers.ex

**Asana task**: [Prediction Suppression: Transit Data API](https://app.asana.com/0/1185117109217413/1209646154006769/f)
- /api/suppressed_predictions/all will now return a list of suppressed predictions for transit data use
- Takes our current suppressed_predictions data and transforms them within the endpoint to get the correct format
- Added a few new test signs for verifying Green and Silver line logic

Added endpoint for Transit Data

---

assets/js/components/Dashboard/PaMessagesPage.tsx
assets/js/components/Dashboard/PredictionSuppressionPage.tsx
assets/js/hooks/useScreenplayContext.tsx
assets/js/models/suppressed_prediction.ts
assets/js/utils/api.ts
assets/tests/setup.ts
config/dev.exs

**Asana task**: [Prediction suppression: Wire up UI state](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1209637020443931?focus=true)
This implements the stateful interactions on the prediction suppression page. Uses the SWR library to do "optimistic updates" for snappy interactions. The state lives in a top-level container because it will be needed on every page to drive the badge number on the left nav (coming in a followup PR)

wire up prediction suppression UI

---

assets/js/components/Dashboard/AlertBanner.tsx
assets/js/components/Dashboard/AlertDetails.tsx
assets/js/components/Dashboard/AlertsPage.tsx
assets/js/components/Dashboard/CopyLinkButton.tsx
assets/js/components/Dashboard/Dashboard.tsx
assets/js/components/Dashboard/PaMessageForm/SelectStationsAndZones/SelectStationsAndZones.tsx
assets/js/components/Dashboard/PendingScreenDetail.tsx
assets/js/components/Dashboard/PendingScreensPage.tsx
assets/js/components/Dashboard/PermanentConfiguration/Workflows/GlEink/ConfigureScreensPage.tsx
assets/js/components/Dashboard/PermanentConfiguration/Workflows/GlEink/GlEinkWorkflow.tsx
assets/js/components/Dashboard/PermanentConfiguration/Workflows/GlEink/StationSelectPage.tsx
assets/js/components/Dashboard/PlaceRowAccordion.tsx
assets/js/components/Dashboard/PlacesPage.tsx
assets/js/components/Dashboard/PredictionSuppressionPage.tsx
assets/js/components/Dashboard/ScreenDetailActionBar.tsx
assets/js/hooks/usePlacesWithPaEss.ts
assets/js/hooks/useScreenplayContext.tsx
assets/tests/components/placeRowAccordion.test.tsx

This refactors the top-level application state to use regular state instead of reducers. Reducers tend to be more verbose, and they only provide extra value in a few narrow use cases (e.g. reducer composition and time-travel debugging), none of which we're using.
The revised code extends the passed Context values with setter callbacks to update the managed state. The result is much more compact and the names/types are more straightforward.
Also reworks the `AlertDetails` page to simplify the code by taking advantage of the new state container.

replace reducers with regular state

---

assets/css/prediction-suppression.module.scss
assets/css/sidebar.module.scss
assets/js/components/Dashboard/PredictionSuppressionPage.tsx
assets/js/components/Dashboard/Sidebar.tsx

**Asana task**: [Prediction suppression: Wire up UI state](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1209637020443931?focus=true)
Description
This adds the numerical badges to the prediction suppression page and the global sidebar.

implement prediction suppression badges

---

assets/eslint.config.mjs
assets/js/components/Dashboard/AlertCard.tsx
assets/js/components/Dashboard/AlertsPage.tsx
assets/js/components/Dashboard/EditPaMessage/EditPaMessage.tsx
assets/js/components/Dashboard/PaMessagesPage.tsx
assets/js/components/Dashboard/PaessDetailContainer.tsx
assets/js/components/Dashboard/PermanentConfiguration/Workflows/GlEink/ConfigureScreensPage.tsx
assets/js/components/Dashboard/PlacesActionBar.tsx
assets/js/components/Dashboard/PredictionSuppressionPage.tsx
assets/js/components/Dashboard/PriorityPicker.tsx
assets/js/components/Dashboard/ScreenDetail.tsx
assets/js/components/Dashboard/Toast.tsx
assets/js/components/OutfrontTakeoverTool/AlertWizard/AlertWizard.tsx
assets/js/components/Tables/MessageTable.tsx
assets/js/hooks/useUpdateAnimation.tsx

This enables the eslint rule to enforce `===` and `!==` usage, and fixes all resulting issues.

enforce strict equality checks

---

docs/tech_specs/suppressed_predictions_api.md

Hi friends! Working on consuming this new API endpoint and noticed a typo in the URL. Thought it might be easier to open a PR instead of DMing one of you on Slack about it.

fix: URL in suppressed-predictions API documention

---

assets/js/components/Dashboard/PredictionSuppressionPage.tsx
lib/screenplay/prediction_suppression.ex

This adds the Mattapan line to the prediction suppression page, which was inadvertently omitted from the original designs.

add Mattapan line to prediction suppression

---

lib/screenplay_web/controllers/suppressed_predictions_api_controller.ex

We were already logging when a prediction suppression is created or updated, but not when one was deleted. This completes the picture.
**Asana task**: https://app.asana.com/1/15492006741476/project/1185117109217413/task/1210707261785843

chore: log deleted prediction suppressions

---

assets/js/components/Dashboard/Dashboard.tsx

**Asana task**: [Screenplay: blank alert update message on Prediction Suppression](https://app.asana.com/1/15492006741476/project/1185117109217422/task/1210601350130555?focus=true)
Description
This excludes the alert banner from showing up on the prediction suppression page, since it's not relevant there.

don't show alert banner on prediction suppression page

---

.github/workflows/ci.yml
.tool-versions
Dockerfile

Node 18 reached End Of Life in April 2025 and no longer receives security updates. Update to Node 22, the current LTS release, which will be supported until mid-2027.
**Asana task**: https://app.asana.com/1/15492006741476/project/1185117109217413/task/1211023063494548

chore: update Node.js version

---

assets/js/components/Dashboard/PaMessageForm/MainForm.tsx
lib/screenplay/pa_messages/pa_message/queries.ex
lib/screenplay/util.ex
test/screenplay/util_test.exs

Due to the addition of limited late-night service, 4:00am should now be considered the start/end of the service day.
This affects:
* when PA messages are considered to be "active" when set to only play on certain days of the week
* the time filled in by the "start/end of service day" controls when a user is creating or editing a PA message
Incidentally reworks a function that determined the current service day to behave better around time zone changes. This used `DateTime.add`, which computes a time difference based on elapsed time, not wall time; on the date of the "fall back" from EDT to EST, shifting time backwards by 3 hours from e.g. 02:30 could land at 00:30 (still on the same day, rather than the previous day as intended).
**Asana task**: …

chore: switch to 4:00am service day boundary

---

assets/css/error-modal.scss
assets/js/components/App.tsx
assets/js/components/Dashboard/Dashboard.tsx
assets/js/components/Dashboard/ErrorModal.tsx
assets/js/components/Dashboard/PaMessageForm/AssociateAlert.tsx
assets/js/components/Dashboard/PendingScreensPage.tsx
assets/js/components/Dashboard/PermanentConfiguration/Workflows/GlEink/ConfigureScreensPage.tsx
assets/js/components/Dashboard/PermanentConfiguration/Workflows/GlEink/GlEinkWorkflow.tsx
assets/js/components/OutfrontTakeoverTool/AlertDashboard/AlertsList.tsx
assets/js/constants/constants.ts
assets/js/hello.ts
assets/js/hooks/useErrorState.tsx
assets/js/utils/api.ts
assets/js/utils/errorHandler.tsx
assets/package-lock.json
assets/package.json
assets/tests/setup.ts
assets/tests/utils/errorHandler.test.tsx

**Asana task**: [Communicate errors to user](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1208769995914082?focus=true)
- Adds `errorHandler.tsx` with a wrapper to handle async functions.
- Updates ErrorModal.tsx to display based on a global `ErrorState`. 
- Note that this PR includes some unused functionality within `withErrorHandling`. Silent errors and retries were used in earlier versions of the changes, but I ended up feeling that none of the updated wrapped methods require them. I left these options in for now, and have them unit tested, in case we want to make use of them in the future.
Error being displayed on modal in the center of Screenplay page:
Multiple errors:

feat: Error handling wrapper to handle and communicate errors to user
