assets/js/components/Dashboard/Sidebar.tsx

**Asana task**: [📺▶️ : 🇵🇱 | Fix OFM takeover link label](https://app.asana.com/0/1185117109217413/1202728175921077/f)
Changed text in link.

fix: Emergency Takeover link text

---

assets/css/screen-detail.scss
assets/js/components/Dashboard/ScreenDetail.tsx
scripts/fetch_places_and_screens.exs

**Asana task**: [📺▶️ | Simulate Solari screens](https://app.asana.com/0/1185117109217413/1202773104374786/f)
This PR does two things: 
1. Alters the data script the split out a Solari screen into all places that it gets data for
2. Adds iframes to each place showing the Solari sim.

feat: Solari sims

---

assets/css/dashboard.scss
assets/css/filter-dropdown.scss
assets/css/place-row.scss
assets/js/components/Dashboard/Dashboard.tsx
assets/js/components/Dashboard/FilterDropdown.tsx
assets/js/components/Dashboard/PlaceRow.tsx
assets/js/constants/constants.ts
assets/js/util.ts
assets/tests/components/filterDropdown.test.tsx

**Asana task**: [📺▶️ : 🇵🇱 | Align filter controls with Places table columns](https://app.asana.com/0/1185117109217413/1202737926527313/f)
Filter dropdowns are now aligned with the column that they are a filter for. I also cleaned up/renamed a few CSS classes so that there is more consistency.

polish: Align filter dropdowns

---

assets/css/filter-dropdown.scss

**Asana task**: [Filter dropdowns: Center clear button icon](https://app.asana.com/0/0/1202839698975984/f)
Left and right padding needed to be removed so the icon could be centered.

polish: Center clear button icon

---

README.md
assets/css/screen-detail.scss
config/dev.exs

**Asana task**: [📺▶️ : 🇵🇱 | Scrollbar in simulations](https://app.asana.com/0/1185117109217413/1202736912335100)
Pairs with: https://github.com/mbta/screens/pull/1481.
TBD whether there should be more or less padding on the sims, now that a scrollbar padding has been added.

Adjust height of screens that need a scrollbar; change default dev port

---

assets/css/filter-dropdown.scss
assets/js/components/Dashboard/Dashboard.tsx
assets/js/components/Dashboard/FilterDropdown.tsx

**Asana task**: [Filter dropdowns: Disable Status filter](https://app.asana.com/0/0/1202839698975985/f)
Status won't be used until overrides are implemented. Disabling the filter until then.

polish: Disable status filter.

---

assets/js/components/OutfrontTakeoverTool/OutfrontTakeoverTool.tsx
lib/screenplay_web/templates/layout/app.html.heex

[Notion](https://www.notion.so/mbta-downtown-crossing/Consider-change-site-title-to-Screenplay-86de5d77041e47be852d5d5b3777ab42)
Changed default title to `Screenplay`. OFT title remains the same but is overriden in frontend.

polish: Screenplay doc title

---

assets/css/place-row.scss

[Notion](https://www.notion.so/mbta-downtown-crossing/Rows-don-t-have-hover-state-bdd69570112543bfabbf0b054e5672f2)
I think the only hover effect is `background-color`. Added that to places that have screens.

polish: PlaceRow hover

---

assets/css/screen-detail.scss

Part 2 of 2 for [this polish task](https://www.notion.so/mbta-downtown-crossing/c879496a39fd4e62969fe1d0eecdfa01?v=f7ad0a8b40784aaebb1aaac3d417bb39&p=506626730932486ca5a83e66c2c59ebf&pm=s).

Added drop-shadow to non-widget screens

---

assets/css/filter-dropdown.scss

[Notion](https://www.notion.so/mbta-downtown-crossing/Different-colors-on-the-dropdown-component-d8f8f18c539d4c6f9e5a71f89f0d8693)
Corrected the color of dropdown items that are not active.

polish: Corrected dropdown item text color.

---

assets/js/components/Dashboard/ScreenDetail.tsx

**Asana task**: [Log screens simulation requests](https://app.asana.com/0/1185117109217413/1202766648515759/f)
Related to https://github.com/mbta/screens/pull/1515.
Added the query param to simulation URLs so logs can capture who made what request.

feat: Add source query param to simulations.

---

assets/js/constants/constants.ts

**Asana task**: [Remove unused filters](https://app.asana.com/0/1185117109217413/1203072885562881/f)
Remove some filters that don't do anything right now.

polish: Remove unused filters

---

assets/js/app.tsx
assets/js/components/App.tsx
assets/package-lock.json
assets/package.json
config/config.exs
config/prod.exs
config/runtime.exs
lib/screenplay_web/controllers/dashboard_controller.ex
lib/screenplay_web/controllers/outfront_takeover_tool/page_controller.ex
lib/screenplay_web/templates/dashboard/index.html.eex
lib/screenplay_web/templates/outfront_takeover_tool/page/index.html.heex

**Asana task**: [Set Up Sentry for Screenplay](https://app.asana.com/0/1185117109217413/1201365885881926/f)
This sets up Sentry for our front-end for Screenplay. No source mapping yet, but at the very least we'll have a way to tell if errors are occurring. DSNs are already set in ECS.

feature: Add Sentry for frontend logs

---

scripts/fetch_places_and_screens.exs

**Asana task**: [[Screenplay] Group screens by stop ID, not stop name](https://app.asana.com/0/1185117109217413/1203093788250254/f)
Updated the script to keep all places with the same name in their own group if the `stop-id`s are different. This should only affect stops that do not have a `parent_station`, which is most bus stops. All other stops should look as they did before the change.

tweak: group places by stop-id

---

assets/js/components/Dashboard/ScreenDetail.tsx

**Asana task**: [Update Splunk E-Ink logging so there are not 2 'source' fields](https://app.asana.com/0/1164574158255689/1203166122404934/f)
See https://github.com/mbta/screens/pull/1537 for details. Only a param name needed tweaking in this project.

tweak: Rename query param.

---

assets/js/components/Dashboard/MapSegment.tsx
assets/js/components/Dashboard/bundled_svg/BranchTop.tsx
assets/js/constants/stationOrder.ts
assets/tests/components/dashboard.test.tsx
assets/tests/places_and_screens.test.json

Second part of [this task](https://app.asana.com/0/1185117109217413/1203364297898378)
Requires an update of the places_and_screens.json to see the updated stick map.

Updated station list for GLX

---

assets/css/alert-card.scss
assets/css/animation.scss
assets/css/screenplay.scss
assets/js/components/Dashboard/AlertCard.tsx
assets/js/components/Dashboard/AlertDetails.tsx
assets/js/components/Dashboard/AlertsPage.tsx
assets/js/components/Dashboard/PlaceRow.tsx
assets/js/components/Dashboard/PlacesPage.tsx
assets/js/hooks/usePrevious.tsx
assets/js/hooks/useUpdateAnimation.tsx

**Asana task**: [[Screenplay] Update data animation](https://app.asana.com/0/1185117109217413/1203279317437020/f)
This PR adds a brief animation to `AlertCard`s and `PlaceRow`s on `AlertDetails`. When an alert has been updated, the `AlertCard` will highlight for a couple of seconds. On the `AlertDetails` page, `PlaceRow`s will highlight as they appear on the list. No animation should occur on page load, only when the page is already loaded and data changes.

feat: Data Update Animations

---

assets/js/components/Dashboard/AlertCard.tsx

[Notion Task](https://www.notion.so/mbta-downtown-crossing/1-places-and-1-screens-grammar-f1386b2ce5d6476e990702e521c60301)
Update grammar on alert card for when the number of places and/or screens is 1

Update grammar on alert card

---

assets/js/util.ts

Notion [task](https://www.notion.so/mbta-downtown-crossing/Logic-for-when-banner-is-shown-4a02be5c16d94cb68137b689fdc7f0d4)
See table in task for new logic.

polish: AlertBanner visibility logic change

---

assets/js/components/Dashboard/AlertDetails.tsx

Notion [task](https://www.notion.so/mbta-downtown-crossing/Wording-in-Alert-Closed-Modal-774abf3efaa9468b9c565535b37777c6)

Adjust wording of alert closed modal

---

assets/css/modal.scss
assets/css/screenplay.scss
assets/css/variables.scss
assets/js/components/Dashboard/AlertDetails.tsx

Notion [task](https://www.notion.so/mbta-downtown-crossing/Alert-closed-modal-overlay-opacity-and-drop-shadow-7538102642e640d480246ae0cc6b84c5).
Modal backdrop needed blurring; dialog needed drop-shadow.

Alerts polish: Fixed modal backdrop, drop-shadow, styles

---

assets/css/alert-banner.scss
assets/css/screenplay.scss
assets/css/sidebar.scss
assets/js/components/Dashboard/AlertBanner.tsx
assets/js/components/Dashboard/AlertCard.tsx
assets/js/components/Dashboard/AlertDetails.tsx
assets/js/components/Dashboard/AlertsPage.tsx
assets/js/components/Dashboard/PlaceRow.tsx
assets/js/components/Dashboard/PlacesPage.tsx
assets/js/components/Dashboard/Sidebar.tsx

Notion [task](https://www.notion.so/mbta-downtown-crossing/Screenplay-Alerts-Polish-d3f44e3eec4346a19f31f24f75fa1ae6?p=7697a510ac38456dbd5b81ca255332af&pm=s).
The icon animation is not covered in this notion task, but a different one. Verifying with Mindy that this solution is as desired.

Polish: icon size / boldness / opacity / animation

---

assets/css/screenplay.scss

Notion [task](https://www.notion.so/mbta-downtown-crossing/Letter-spacing-on-buttons-with-lowercase-text-2d9979a9c97f4571bee682c2f696857c)
Tweaked `letter-spacing` on buttons just a tad.

polish: Button letter-spacing

---

assets/css/alert-card.scss
assets/js/components/Dashboard/AlertCard.tsx

Notion [task](https://www.notion.so/mbta-downtown-crossing/Identify-that-an-alert-is-recurring-cb6949292d00474781c2d2aa161cf1e9)
Added some test to `AlertCard`s showing if an alert is recurring.

polish: Recurring AlertCard

---

lib/screenplay/config/local_fetch.ex

**Asana task**: ad hoc
Just making the developer quality of life a little nicer~~
When e.g. `places_and_screens.json` is missing, you'll now get an informative message in your console:
```
warning: Couldn't read local file /Users/jzimbel/git/screenplay/_build/dev/lib/screenplay/priv/places_and_screens.json for spec :local_config_file_spec. Error reported: :enoent
```
instead of just "no match of right hand side value: :error" way up in the controller.

Yell when a necessary file is missing for local dev

---

README.md
config/config.exs
config/dev.exs
config/test.exs

doc: Add required env vars to README; remove unused config

---

assets/css/screen-detail.scss
assets/js/components/Dashboard/PlaceRow.tsx
assets/js/constants/constants.ts

**Asana task**: [[DUP v2] Make v2 DUP screens show up correctly in Screenplay](https://app.asana.com/0/1185117109217413/1203885464554557)
Simple: added dup_v2 support in Screenplay (tweaked variables, mainly.) The primary for the task is in the Screens repo.

Added Screenplay's support of dup_v2

---

scripts/fetch_places_and_screens.exs

Added `dup_v2` function patterns to script.

Added dup_v2 patterns to script.

---

assets/js/app.tsx

**Asana task**: [Configure Fullstory to capture iframes](https://app.asana.com/0/1185117109217413/1204351329872461/f)
This flag should be all we need to allow FS to capture iframe content. Will need to deploy to prod to confirm it works.

fix: Fullstory iframe captures

---

assets/css/screen-detail-action-bar.scss
assets/js/components/Dashboard/ScreenDetailActionBar.tsx

Accidentally overwrote the drop-down background colors in my last PR.

Adhoc: Fix dropdown background colors

---

docs/tech_specs/configuration_backend_approach.md

**Asana task**: [[Screenplay] Brainstorm: configuring screens](https://app.asana.com/0/1185117109217413/1205058023431637/f)
Description
This RFC is for outlining at the high-level an approach for allowing for Screenplay to reference code from Screens.

RFC: Selecting an approach for sharing code between Screens and Screenplay

---

assets/css/screen-detail.scss
assets/js/components/Dashboard/PlaceRow.tsx
assets/js/constants/constants.ts

**Asana task**: [Make triptych/crowding app show up correctly in Screenplay](https://app.asana.com/0/1185117109217413/1205301761265225/f)
Added necessary filters and labels for Triptychs and gave the iframe enough height so it does not scroll vertically.

feat: Triptych sims

---

lib/screenplay/config/config.ex
lib/screenplay_web/controllers/config_controller.ex
lib/screenplay_web/router.ex

**Asana task**: [Stub out functions for Permanent Config operations](https://app.asana.com/0/1185117109217413/1205700210661285/f)
Description
Sets up routes and controller actions to be used for permanent config. Also adds a new file that will contain the business logic for each action.

Stub out permanent config operations

---

assets/js/components/Dashboard/ScreenDetail.tsx

**Asana task**: [Name triptychs in Screenplay by direction](https://app.asana.com/0/1185117109217413/1205717671578677/f)
Added platform direction to Triptych screens.

tweak: Triptch Platform direction

---

assets/css/alert-card.scss
assets/css/screenplay-container.scss
assets/css/workflow.scss
assets/js/components/App.tsx
assets/js/components/Dashboard/PendingScreensPage.tsx
assets/js/components/Dashboard/PermanentConfiguration/BottomActionBar.tsx
assets/js/components/Dashboard/PermanentConfiguration/ConfigureScreensPage.tsx
assets/js/components/Dashboard/PermanentConfiguration/SelectScreenType.tsx
assets/js/components/Dashboard/PermanentConfiguration/Workflows/GlEink/ConfigureScreensPage.tsx
assets/js/components/Dashboard/PermanentConfiguration/Workflows/GlEink/GlEinkWorkflow.tsx
lib/screenplay_web/router.ex

**Asana task**: [[Perm config] Edit station's pending screens page](https://app.asana.com/0/1185117109217413/1206114010686515/f)
This PR includes most of the work needed for the "Edit" button to work on the Pending Screens Page. The actual button does not exist quite yet (will be added in this [task](https://app.asana.com/0/1185117109217413/1205973195471510/f)), but the logic would not change once the button is available.

feat: Edit Pending Screens

---

assets/js/components/Dashboard/PendingScreensPlaceRowAccordion.tsx

**Asana task**: Permanent Config GL E-Ink QA

Permanent config workflow polish: Prevent pending screens accordion from toggling when header buttons are clicked

---

lib/screenplay_web/controllers/config_controller.ex

**Asana task**: Permanent Config GL E-Ink QA
Was comparing the client-provided etag with the pending config file's version ID. Need to compare etag with etag!

Permanent config workflow polish: Compare etag with etag

---

assets/js/components/Dashboard/Sidebar.tsx

**Asana task**: polish
Selected tab styling expects slashes to be removed.

 Permanent config workflow polish: Sidebar selected tab stying

---

assets/css/dashboard/alerts-page.scss
assets/css/screenplay-container.scss

**Asana task**: polish
This should fix bg color on all pages. I went through a bunch of different layout combos and they all look good.

Tweaked styles so bg color takes up whole page height.

---

docs/tech_specs/pa_message_api.md

**Asana task**: [API Call Definition](https://app.asana.com/0/1185117109217413/1206860070503127/f)
This PR adds some documentation for the new endpoint RTS will use to retrieve active PA messages from Screenplay.

doc: Active Message API doc

---

assets/js/components/Dashboard/Sidebar.tsx

Quick rename and icon change for the Perm Config tab. https://mbta.slack.com/archives/C039ARUM48H/p1714750883534699

tweak: Perm Config tab rename

---

config/config.exs
lib/screenplay/ueberauth/strategy/fake.ex
lib/screenplay_web/auth_manager/auth_manager.ex
lib/screenplay_web/auth_manager/error_handler.ex
lib/screenplay_web/auth_manager/pipeline.ex
lib/screenplay_web/controllers/auth_controller.ex
mix.exs
test/screenplay_web/auth_manager/error_handler_test.exs

Some unexpected Sentry errors are popping up after these changes were merged. I will investigate, but wanted to get this out of `main` until I can find the root cause.

revert: Auth rework

---

assets/css/dashboard/date-picker.scss
assets/css/dashboard/new-pa-message-page/new-pa-message-page.scss
assets/css/dashboard/pa-messages-page.scss
assets/css/dashboard/time-picker.scss
assets/js/components/Dashboard/DatePicker.tsx
assets/js/components/Dashboard/PaMessaging/NewPaMessagePage/DaysPicker.tsx
assets/js/components/Dashboard/PaMessaging/NewPaMessagePage/IntervalPicker.tsx
assets/js/components/Dashboard/PaMessaging/NewPaMessagePage/MessageTextBox.tsx
assets/js/components/Dashboard/PaMessaging/NewPaMessagePage/NewPaMessagePage.tsx
assets/js/components/Dashboard/PaMessaging/NewPaMessagePage/PriorityPicker.tsx
assets/js/components/Dashboard/PaMessaging/PaMessagesPage.tsx
assets/js/components/Dashboard/TimePicker.tsx

This PR includes various improvements to form structure and accessibility. Changes were motivated by some followup [comments](https://github.com/mbta/screenplay/pull/361#pullrequestreview-2103252475) in the previous PR. While this doesn't correct all accessibility issues on the page, it is a good start and more changes can be included as the feature is built.

followup: New PA Message page

---

lib/screenplay_web/controllers/alerts_api_controller.ex

Came across [this](https://mbtace.sentry.io/issues/5611710385/events/bca6f7e2151b42e8958342e34b363ae2/) Sentry error today. After some digging, I saw that a timeout cause the issue. There really is no need to make a fetch here now that we have the cache. Switched the fetch to grab alerts from cache.

Switch to cache to avoid unnecessary fetch errors.

---

assets/package-lock.json

Addresses [this](https://github.com/mbta/screenplay/security/dependabot/37) Dependabot alert.

update: Address braces vulnerability.

---

scripts/paess_labels.json

See: https://github.com/mbta/realtime_signs/pull/805

chore: update PA/ESS labels for new lab sign IDs

---

assets/css/dashboard/error-toast.scss
assets/css/dashboard/new-pa-message/new-pa-message-page.scss
assets/css/dashboard/new-pa-message/new-pa-message.scss
assets/css/screenplay.scss
assets/css/variables.scss
assets/js/components/Dashboard/ErrorToast.tsx
assets/js/components/Dashboard/IntervalPicker.tsx
assets/js/components/Dashboard/MessageTextBox.tsx
assets/js/components/Dashboard/NewPaMessage/NewPaMessage.tsx
assets/js/components/Dashboard/NewPaMessage/NewPaMessagePage.tsx
assets/js/components/Dashboard/PaMessagesPage.tsx
assets/js/models/pa_message.ts
assets/js/utils/api.ts

This PR adds form submission and validation for new PA Messages on the client. An invalid PA Message object should not make it to the server, but in case it does the toast has been enhanced to show the errors from the Ecto.Changeset.

feat: PA Message client form submission

---

assets/css/dashboard/error-toast.scss
assets/css/dashboard/new-pa-message/select-zones-page.scss
assets/js/components/Dashboard/Dashboard.tsx
assets/js/components/Dashboard/ErrorToast.tsx
assets/js/components/Dashboard/NewPaMessage/NewPaMessage.tsx
assets/js/components/Dashboard/NewPaMessage/NewPaMessagePage.tsx
assets/js/components/Dashboard/NewPaMessage/StationsAndZones/SelectStationsPage.tsx
assets/js/components/Dashboard/NewPaMessage/StationsAndZones/SelectZonesPage.tsx
assets/js/components/Dashboard/PaMessagesPage.tsx
assets/js/models/pa_message.ts
assets/js/util.ts
assets/js/utils/api.ts
lib/screenplay/pa_messages/pa_message.ex
lib/screenplay/pa_messages/pa_message/queries.ex
priv/repo/migrations/20240812182216_change_datetime_column_names.exs
priv/repo/seeds.exs
test/screenplay/pa_messages_test.exs
test/screenplay_web/controllers/pa_messages_api_controller_test.exs
test/support/factory.ex

This PR addresses some QA items on [this](https://miro.com/app/board/uXjVK0Nq3mE=/) Miro board as well as some issues I caught. See commits for exact issues.

chore: Zones QA

---

assets/js/components/Dashboard/PaMessagesPage.tsx

Adds filters on "Service type" to the PA messages page where a "Service type" is a label for one or more routes. Maps these service types back to the set of routes using the same logic found in the Select Stations/Zones views. 
https://github.com/user-attachments/assets/005b48fa-52fb-4c07-85f6-a098258cfd1f
**Asana task**: [Message Page Filtering](https://app.asana.com/0/1185117109217413/1207154234320378/f)

feat: adds UI to filter PA messages on service type

---

scripts/pull_configs.sh

This file was moved from static to S3 configuration in 478f1b9.

dev: update `pull_configs` to include new file

---

assets/css/dashboard/pa-messages-page.scss
assets/js/components/Dashboard/PaMessagesPage.tsx

**Asana task**: [Clean up Message Management Functions](https://app.asana.com/0/1185117109217413/1207983141001734/f)
Description
This PR removes two columns that are now out of scope for the first release

Clean up message management functions

---

assets/js/components/Dashboard/PaMessageForm/MainForm.tsx
assets/js/components/Dashboard/PaMessageForm/PaMessageForm.tsx

**Asana task**: [PA Message UI: Consistent Audio Review Requirements](https://app.asana.com/0/1207094698667699/1208141422484879/f)
Any changes to Visual Text or Phonetic Text when creating or editing PA messages now reset the audio review status to "Unreviewed".

fix: any updates to text reset review status

---

assets/css/dashboard/pa-messages-page.scss
assets/js/components/Dashboard/PaMessagesPage.tsx

While working on #483, I noticed some styles were off when compared to the [Figma](https://www.figma.com/design/P6RZ1AJWk7P98D6IFDK9Ik/PA%2FESS-Modernization?node-id=8909-76990&t=JmB8WVTpztQu2d2R-4). Took the opportunity to clean things up a bit.

chore: PA Message table styles

---

assets/css/dashboard/kebab-menu.scss
assets/css/dashboard/pa-messages-page.scss
assets/js/components/Dashboard/KebabMenu.tsx
assets/js/components/Dashboard/PaMessagesPage.tsx

Mary expressed some concerns over styles [here](https://mbta.slack.com/archives/C039ARUM48H/p1730912294881359?thread_ts=1730904072.858599&cid=C039ARUM48H). Made some adjustments to the layout so what she called out is implemented correctly.

fix: Actions column styles

---

.github/pull_request_template.md

Added a checklist item to PR template.

chore: Update PR Template

---

assets/css/dashboard/new-pa-message/new-pa-message.scss
assets/css/dashboard/new-pa-message/select-zones-page.scss
assets/css/pa-messages.module.scss
assets/css/variables.scss
assets/js/components/Dashboard/DaysPicker.tsx
assets/js/components/Dashboard/EditPaMessage/EditPaMessage.tsx
assets/js/components/Dashboard/IntervalPicker.tsx
assets/js/components/Dashboard/PaMessageForm/MainForm.tsx
assets/js/components/Dashboard/PaMessageForm/PaMessageForm.tsx
assets/js/components/Dashboard/PaMessageForm/SelectStationsAndZones/PlaceZonesRow.tsx
assets/js/components/Dashboard/PaMessageForm/SelectStationsAndZones/RouteColumn.tsx
assets/js/components/Dashboard/PaMessageForm/SelectStationsAndZones/SelectStationsAndZones.tsx
assets/js/components/Dashboard/PaMessageForm/SelectStationsAndZones/SelectStationsPage.tsx
assets/js/components/Dashboard/PaMessageForm/SelectStationsAndZones/SelectZonesPage.tsx
assets/js/components/Dashboard/PaMessageForm/SelectStationsAndZones/SelectedStationsSummary.tsx
assets/js/components/Dashboard/PaMessageForm/SelectStationsAndZones/SignButtonGroup.tsx
assets/js/components/Dashboard/PaMessageForm/SelectStationsAndZones/StationGroupCheckbox.tsx
assets/js/components/Dashboard/PaMessageForm/SelectedSignsByRouteTags.tsx
assets/js/components/Dashboard/PaMessagesPage.tsx
assets/js/components/Dashboard/PriorityPicker.tsx
assets/js/components/Dashboard/Sidebar.tsx
assets/js/utils/auth.ts

**Asana task**: [Read-only mode for PA Message workflow](https://app.asana.com/0/1185117109217413/1208981851846577/f)
Description
Prior to this change, only PA Message admins were able to access the PA Message flow. With this change, all users will now be able to access the PA Message flow, but non-admin users will get a read-only experience.

PA message flow read only

---

assets/css/prediction-suppression.module.scss
assets/js/components/Dashboard/PredictionSuppressionPage.tsx
assets/js/utils/auth.ts
lib/screenplay_web/templates/layout/app.html.heex

**Asana task**: [Prediction suppression: Wire up UI state](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1209637020443931?focus=true)
See title

implement read-only mode for prediction suppression

---

lib/screenplay/places/builder.ex

Reduce the number of special cases for specific screen types and derive stop IDs "generically" from Header, Footer, Alerts, or Departures widget configuration.
The remaining special cases are:
* DUPs, which have a unique configuration shape for departures
* Elevator screens, which need an API call to look up their stop ID

chore: improve screen stop ID logic

---

.tool-versions
Dockerfile
mix.exs
test/screenplay/places/builder_test.exs
test/screenplay/suppressed_predictions_test.exs

**Asana task**: [Update screenplay erlang and elixir versions](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1210451405410755?focus=true)
- Also update Alpine version
- Removed explict package adding and instead use erlang/alpine package
- Fixed tests by moving some objects in proper order
Description

Update elixir to 1.17.3 and erlang to 27.3.4
